/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  EpurchasePrsIndex200,
  EpurchasePrsIndex502,
  EpurchasePrsIndexParams,
  EpurchasePrsShow200,
  EpurchasePrsShow502,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type epurchasePrsIndexResponse200 = {
  data: EpurchasePrsIndex200
  status: 200
}

export type epurchasePrsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchasePrsIndexResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type epurchasePrsIndexResponse502 = {
  data: EpurchasePrsIndex502
  status: 502
}

export type epurchasePrsIndexResponseSuccess = (epurchasePrsIndexResponse200) & {
  headers: Headers;
};
export type epurchasePrsIndexResponseError = (epurchasePrsIndexResponse401 | epurchasePrsIndexResponse422 | epurchasePrsIndexResponse502) & {
  headers: Headers;
};

export type epurchasePrsIndexResponse = (epurchasePrsIndexResponseSuccess | epurchasePrsIndexResponseError)

export const getEpurchasePrsIndexUrl = (params?: EpurchasePrsIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/prs?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/prs`
}

/**
 * @summary Read-only proxy of the upstream purchase requisition list (server-side paging/search)
 */
export const epurchasePrsIndex = async (params?: EpurchasePrsIndexParams, options?: RequestInit): Promise<epurchasePrsIndexResponse> => {

  const res = await fetch(getEpurchasePrsIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchasePrsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchasePrsIndexResponse
}





export const getEpurchasePrsIndexQueryKey = (params?: EpurchasePrsIndexParams,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/prs`, ...(params ? [params] : [])
    ] as const;
    }


export const getEpurchasePrsIndexQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePrsIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePrsIndex>>> = ({ signal }) => epurchasePrsIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePrsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePrsIndex>>>
export type EpurchasePrsIndexQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502


export function useEpurchasePrsIndex<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params: undefined |  EpurchasePrsIndexParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePrsIndex>>,
          TError,
          Awaited<ReturnType<typeof epurchasePrsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsIndex<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePrsIndex>>,
          TError,
          Awaited<ReturnType<typeof epurchasePrsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsIndex<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of the upstream purchase requisition list (server-side paging/search)
 */

export function useEpurchasePrsIndex<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePrsIndexQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEpurchasePrsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePrsIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePrsIndex>>> = ({ signal }) => epurchasePrsIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePrsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePrsIndex>>>
export type EpurchasePrsIndexSuspenseQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502


export function useEpurchasePrsIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params: undefined |  EpurchasePrsIndexParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of the upstream purchase requisition list (server-side paging/search)
 */

export function useEpurchasePrsIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePrsIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePrsIndex502>(
 params?: EpurchasePrsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePrsIndexSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type epurchasePrsShowResponse200 = {
  data: EpurchasePrsShow200
  status: 200
}

export type epurchasePrsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchasePrsShowResponse502 = {
  data: EpurchasePrsShow502
  status: 502
}

export type epurchasePrsShowResponseSuccess = (epurchasePrsShowResponse200) & {
  headers: Headers;
};
export type epurchasePrsShowResponseError = (epurchasePrsShowResponse401 | epurchasePrsShowResponse502) & {
  headers: Headers;
};

export type epurchasePrsShowResponse = (epurchasePrsShowResponseSuccess | epurchasePrsShowResponseError)

export const getEpurchasePrsShowUrl = (prId: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/prs/${prId}`
}

/**
 * @summary Read-only proxy of one upstream purchase requisition's line items.
The route constrains {prId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */
export const epurchasePrsShow = async (prId: string, options?: RequestInit): Promise<epurchasePrsShowResponse> => {

  const res = await fetch(getEpurchasePrsShowUrl(prId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchasePrsShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchasePrsShowResponse
}





export const getEpurchasePrsShowQueryKey = (prId: string,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/prs/${prId}`
    ] as const;
    }


export const getEpurchasePrsShowQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(prId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePrsShowQueryKey(prId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePrsShow>>> = ({ signal }) => epurchasePrsShow(prId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: prId !== null && prId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePrsShowQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePrsShow>>>
export type EpurchasePrsShowQueryError = AuthenticationExceptionResponse | EpurchasePrsShow502


export function useEpurchasePrsShow<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePrsShow>>,
          TError,
          Awaited<ReturnType<typeof epurchasePrsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsShow<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePrsShow>>,
          TError,
          Awaited<ReturnType<typeof epurchasePrsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsShow<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of one upstream purchase requisition's line items.
The route constrains {prId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */

export function useEpurchasePrsShow<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePrsShowQueryOptions(prId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEpurchasePrsShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(prId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePrsShowQueryKey(prId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePrsShow>>> = ({ signal }) => epurchasePrsShow(prId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePrsShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePrsShow>>>
export type EpurchasePrsShowSuspenseQueryError = AuthenticationExceptionResponse | EpurchasePrsShow502


export function useEpurchasePrsShowSuspense<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsShowSuspense<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePrsShowSuspense<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of one upstream purchase requisition's line items.
The route constrains {prId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */

export function useEpurchasePrsShowSuspense<TData = Awaited<ReturnType<typeof epurchasePrsShow>>, TError = AuthenticationExceptionResponse | EpurchasePrsShow502>(
 prId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePrsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePrsShowSuspenseQueryOptions(prId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






