/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ApprovalsInbox200,
  ApprovalsInboxCount200,
  ApprovalsInboxCountParams,
  ApprovalsInboxParams,
  ApprovalsOutbox200,
  ApprovalsOutboxParams,
  ApprovalsPreview200,
  ApprovalsPreviewParams,
  ApprovalsRequestsActions200,
  ApprovalsRequestsIndex200,
  ApprovalsRequestsIndexParams,
  ApprovalsRequestsShow200,
  ApprovalsRequestsStore201,
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StoreApprovalActionRequest,
  StoreApprovalRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type approvalsPreviewResponse200 = {
  data: ApprovalsPreview200
  status: 200
}

export type approvalsPreviewResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsPreviewResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsPreviewResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsPreviewResponseSuccess = (approvalsPreviewResponse200) & {
  headers: Headers;
};
export type approvalsPreviewResponseError = (approvalsPreviewResponse401 | approvalsPreviewResponse403 | approvalsPreviewResponse422) & {
  headers: Headers;
};

export type approvalsPreviewResponse = (approvalsPreviewResponseSuccess | approvalsPreviewResponseError)

export const getApprovalsPreviewUrl = (params: ApprovalsPreviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/approvals/preview?${stringifiedParams}` : `http://localhost:8000/api/v1/approvals/preview`
}

export const approvalsPreview = async (params: ApprovalsPreviewParams, options?: RequestInit): Promise<approvalsPreviewResponse> => {

  const res = await fetch(getApprovalsPreviewUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsPreviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsPreviewResponse
}





export const getApprovalsPreviewQueryKey = (params?: ApprovalsPreviewParams,) => {
    return [
    `http://localhost:8000/api/v1/approvals/preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getApprovalsPreviewQueryOptions = <TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params: ApprovalsPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsPreviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsPreview>>> = ({ signal }) => approvalsPreview(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsPreview>>>
export type ApprovalsPreviewQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsPreview<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsPreview>>,
          TError,
          Awaited<ReturnType<typeof approvalsPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsPreview<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsPreview>>,
          TError,
          Awaited<ReturnType<typeof approvalsPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsPreview<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsPreview<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsPreviewQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsPreviewSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params: ApprovalsPreviewParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsPreviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsPreview>>> = ({ signal }) => approvalsPreview(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsPreviewSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsPreview>>>
export type ApprovalsPreviewSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsPreviewSuspense<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsPreviewSuspense<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsPreviewSuspense<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsPreviewSuspense<TData = Awaited<ReturnType<typeof approvalsPreview>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: ApprovalsPreviewParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsPreviewSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsInboxResponse200 = {
  data: ApprovalsInbox200
  status: 200
}

export type approvalsInboxResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsInboxResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsInboxResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsInboxResponseSuccess = (approvalsInboxResponse200) & {
  headers: Headers;
};
export type approvalsInboxResponseError = (approvalsInboxResponse401 | approvalsInboxResponse403 | approvalsInboxResponse422) & {
  headers: Headers;
};

export type approvalsInboxResponse = (approvalsInboxResponseSuccess | approvalsInboxResponseError)

export const getApprovalsInboxUrl = (params?: ApprovalsInboxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/approvals/inbox?${stringifiedParams}` : `http://localhost:8000/api/v1/approvals/inbox`
}

export const approvalsInbox = async (params?: ApprovalsInboxParams, options?: RequestInit): Promise<approvalsInboxResponse> => {

  const res = await fetch(getApprovalsInboxUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsInboxResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsInboxResponse
}





export const getApprovalsInboxQueryKey = (params?: ApprovalsInboxParams,) => {
    return [
    `http://localhost:8000/api/v1/approvals/inbox`, ...(params ? [params] : [])
    ] as const;
    }


export const getApprovalsInboxQueryOptions = <TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsInboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsInboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsInbox>>> = ({ signal }) => approvalsInbox(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsInboxQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsInbox>>>
export type ApprovalsInboxQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsInbox<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsInboxParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsInbox>>,
          TError,
          Awaited<ReturnType<typeof approvalsInbox>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInbox<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsInbox>>,
          TError,
          Awaited<ReturnType<typeof approvalsInbox>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInbox<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsInbox<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsInboxQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsInboxSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsInboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsInboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsInbox>>> = ({ signal }) => approvalsInbox(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsInboxSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsInbox>>>
export type ApprovalsInboxSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsInboxSuspense<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsInboxParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxSuspense<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxSuspense<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsInboxSuspense<TData = Awaited<ReturnType<typeof approvalsInbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsInboxSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsInboxCountResponse200 = {
  data: ApprovalsInboxCount200
  status: 200
}

export type approvalsInboxCountResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsInboxCountResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsInboxCountResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsInboxCountResponseSuccess = (approvalsInboxCountResponse200) & {
  headers: Headers;
};
export type approvalsInboxCountResponseError = (approvalsInboxCountResponse401 | approvalsInboxCountResponse403 | approvalsInboxCountResponse422) & {
  headers: Headers;
};

export type approvalsInboxCountResponse = (approvalsInboxCountResponseSuccess | approvalsInboxCountResponseError)

export const getApprovalsInboxCountUrl = (params?: ApprovalsInboxCountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/approvals/inbox/count?${stringifiedParams}` : `http://localhost:8000/api/v1/approvals/inbox/count`
}

export const approvalsInboxCount = async (params?: ApprovalsInboxCountParams, options?: RequestInit): Promise<approvalsInboxCountResponse> => {

  const res = await fetch(getApprovalsInboxCountUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsInboxCountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsInboxCountResponse
}





export const getApprovalsInboxCountQueryKey = (params?: ApprovalsInboxCountParams,) => {
    return [
    `http://localhost:8000/api/v1/approvals/inbox/count`, ...(params ? [params] : [])
    ] as const;
    }


export const getApprovalsInboxCountQueryOptions = <TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsInboxCountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsInboxCount>>> = ({ signal }) => approvalsInboxCount(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsInboxCountQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsInboxCount>>>
export type ApprovalsInboxCountQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsInboxCount<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsInboxCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsInboxCount>>,
          TError,
          Awaited<ReturnType<typeof approvalsInboxCount>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxCount<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsInboxCount>>,
          TError,
          Awaited<ReturnType<typeof approvalsInboxCount>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxCount<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsInboxCount<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsInboxCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsInboxCountSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsInboxCountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsInboxCount>>> = ({ signal }) => approvalsInboxCount(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsInboxCountSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsInboxCount>>>
export type ApprovalsInboxCountSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsInboxCountSuspense<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsInboxCountParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxCountSuspense<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsInboxCountSuspense<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsInboxCountSuspense<TData = Awaited<ReturnType<typeof approvalsInboxCount>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsInboxCountParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsInboxCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsInboxCountSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsOutboxResponse200 = {
  data: ApprovalsOutbox200
  status: 200
}

export type approvalsOutboxResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsOutboxResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsOutboxResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsOutboxResponseSuccess = (approvalsOutboxResponse200) & {
  headers: Headers;
};
export type approvalsOutboxResponseError = (approvalsOutboxResponse401 | approvalsOutboxResponse403 | approvalsOutboxResponse422) & {
  headers: Headers;
};

export type approvalsOutboxResponse = (approvalsOutboxResponseSuccess | approvalsOutboxResponseError)

export const getApprovalsOutboxUrl = (params?: ApprovalsOutboxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/approvals/outbox?${stringifiedParams}` : `http://localhost:8000/api/v1/approvals/outbox`
}

export const approvalsOutbox = async (params?: ApprovalsOutboxParams, options?: RequestInit): Promise<approvalsOutboxResponse> => {

  const res = await fetch(getApprovalsOutboxUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsOutboxResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsOutboxResponse
}





export const getApprovalsOutboxQueryKey = (params?: ApprovalsOutboxParams,) => {
    return [
    `http://localhost:8000/api/v1/approvals/outbox`, ...(params ? [params] : [])
    ] as const;
    }


export const getApprovalsOutboxQueryOptions = <TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsOutboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsOutboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsOutbox>>> = ({ signal }) => approvalsOutbox(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsOutboxQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsOutbox>>>
export type ApprovalsOutboxQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsOutbox<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsOutboxParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsOutbox>>,
          TError,
          Awaited<ReturnType<typeof approvalsOutbox>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsOutbox<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsOutbox>>,
          TError,
          Awaited<ReturnType<typeof approvalsOutbox>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsOutbox<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsOutbox<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsOutboxQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsOutboxSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsOutboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsOutboxQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsOutbox>>> = ({ signal }) => approvalsOutbox(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsOutboxSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsOutbox>>>
export type ApprovalsOutboxSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsOutboxSuspense<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsOutboxParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsOutboxSuspense<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsOutboxSuspense<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsOutboxSuspense<TData = Awaited<ReturnType<typeof approvalsOutbox>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsOutboxParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsOutbox>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsOutboxSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsRequestsIndexResponse200 = {
  data: ApprovalsRequestsIndex200
  status: 200
}

export type approvalsRequestsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsRequestsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsRequestsIndexResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsRequestsIndexResponseSuccess = (approvalsRequestsIndexResponse200) & {
  headers: Headers;
};
export type approvalsRequestsIndexResponseError = (approvalsRequestsIndexResponse401 | approvalsRequestsIndexResponse403 | approvalsRequestsIndexResponse422) & {
  headers: Headers;
};

export type approvalsRequestsIndexResponse = (approvalsRequestsIndexResponseSuccess | approvalsRequestsIndexResponseError)

export const getApprovalsRequestsIndexUrl = (params?: ApprovalsRequestsIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/approvals/requests?${stringifiedParams}` : `http://localhost:8000/api/v1/approvals/requests`
}

export const approvalsRequestsIndex = async (params?: ApprovalsRequestsIndexParams, options?: RequestInit): Promise<approvalsRequestsIndexResponse> => {

  const res = await fetch(getApprovalsRequestsIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsRequestsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsRequestsIndexResponse
}





export const getApprovalsRequestsIndexQueryKey = (params?: ApprovalsRequestsIndexParams,) => {
    return [
    `http://localhost:8000/api/v1/approvals/requests`, ...(params ? [params] : [])
    ] as const;
    }


export const getApprovalsRequestsIndexQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsIndex>>> = ({ signal }) => approvalsRequestsIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsIndex>>>
export type ApprovalsRequestsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsRequestsIndex<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsRequestsIndexParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsIndex<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsIndex<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsIndex<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsIndexQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsRequestsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsIndex>>> = ({ signal }) => approvalsRequestsIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsIndex>>>
export type ApprovalsRequestsIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsRequestsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: undefined |  ApprovalsRequestsIndexParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params?: ApprovalsRequestsIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsIndexSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsRequestsStoreResponse201 = {
  data: ApprovalsRequestsStore201
  status: 201
}

export type approvalsRequestsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsRequestsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsRequestsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsRequestsStoreResponseSuccess = (approvalsRequestsStoreResponse201) & {
  headers: Headers;
};
export type approvalsRequestsStoreResponseError = (approvalsRequestsStoreResponse401 | approvalsRequestsStoreResponse403 | approvalsRequestsStoreResponse422) & {
  headers: Headers;
};

export type approvalsRequestsStoreResponse = (approvalsRequestsStoreResponseSuccess | approvalsRequestsStoreResponseError)

export const getApprovalsRequestsStoreUrl = () => {




  return `http://localhost:8000/api/v1/approvals/requests`
}

export const approvalsRequestsStore = async (storeApprovalRequest: StoreApprovalRequest, options?: RequestInit): Promise<approvalsRequestsStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getApprovalsRequestsStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeApprovalRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsRequestsStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsRequestsStoreResponse
}





export const getApprovalsRequestsStoreQueryKey = (storeApprovalRequest?: StoreApprovalRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/approvals/requests`, storeApprovalRequest
    ] as const;
    }


export const getApprovalsRequestsStoreQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(storeApprovalRequest: StoreApprovalRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsStoreQueryKey(storeApprovalRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsStore>>> = ({ signal }) => approvalsRequestsStore(storeApprovalRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsStoreQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsStore>>>
export type ApprovalsRequestsStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsRequestsStore<TData = Awaited<ReturnType<typeof approvalsRequestsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalRequest: StoreApprovalRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsStore>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsStore<TData = Awaited<ReturnType<typeof approvalsRequestsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalRequest: StoreApprovalRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsStore>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsStore<TData = Awaited<ReturnType<typeof approvalsRequestsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalRequest: StoreApprovalRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsStore<TData = Awaited<ReturnType<typeof approvalsRequestsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalRequest: StoreApprovalRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsStoreQueryOptions(storeApprovalRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsRequestsShowResponse200 = {
  data: ApprovalsRequestsShow200
  status: 200
}

export type approvalsRequestsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsRequestsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsRequestsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type approvalsRequestsShowResponseSuccess = (approvalsRequestsShowResponse200) & {
  headers: Headers;
};
export type approvalsRequestsShowResponseError = (approvalsRequestsShowResponse401 | approvalsRequestsShowResponse403 | approvalsRequestsShowResponse404) & {
  headers: Headers;
};

export type approvalsRequestsShowResponse = (approvalsRequestsShowResponseSuccess | approvalsRequestsShowResponseError)

export const getApprovalsRequestsShowUrl = (request: string,) => {




  return `http://localhost:8000/api/v1/approvals/requests/${request}`
}

export const approvalsRequestsShow = async (request: string, options?: RequestInit): Promise<approvalsRequestsShowResponse> => {

  const res = await fetch(getApprovalsRequestsShowUrl(request),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsRequestsShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsRequestsShowResponse
}





export const getApprovalsRequestsShowQueryKey = (request: string,) => {
    return [
    `http://localhost:8000/api/v1/approvals/requests/${request}`
    ] as const;
    }


export const getApprovalsRequestsShowQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(request: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsShowQueryKey(request);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsShow>>> = ({ signal }) => approvalsRequestsShow(request, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: request !== null && request !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsShowQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsShow>>>
export type ApprovalsRequestsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useApprovalsRequestsShow<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsShow>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsShow<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsShow>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsShow<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsShow<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsShowQueryOptions(request,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsRequestsShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(request: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsShowQueryKey(request);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsShow>>> = ({ signal }) => approvalsRequestsShow(request, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsShow>>>
export type ApprovalsRequestsShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useApprovalsRequestsShowSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsShowSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsShowSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsShowSuspense<TData = Awaited<ReturnType<typeof approvalsRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 request: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsShowSuspenseQueryOptions(request,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsRequestsActionsResponse200 = {
  data: ApprovalsRequestsActions200
  status: 200
}

export type approvalsRequestsActionsResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsRequestsActionsResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsRequestsActionsResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type approvalsRequestsActionsResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsRequestsActionsResponseSuccess = (approvalsRequestsActionsResponse200) & {
  headers: Headers;
};
export type approvalsRequestsActionsResponseError = (approvalsRequestsActionsResponse401 | approvalsRequestsActionsResponse403 | approvalsRequestsActionsResponse404 | approvalsRequestsActionsResponse422) & {
  headers: Headers;
};

export type approvalsRequestsActionsResponse = (approvalsRequestsActionsResponseSuccess | approvalsRequestsActionsResponseError)

export const getApprovalsRequestsActionsUrl = (approval: string,) => {




  return `http://localhost:8000/api/v1/approvals/requests/${approval}/actions`
}

export const approvalsRequestsActions = async (approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options?: RequestInit): Promise<approvalsRequestsActionsResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getApprovalsRequestsActionsUrl(approval),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeApprovalActionRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsRequestsActionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsRequestsActionsResponse
}





export const getApprovalsRequestsActionsQueryKey = (approval: string,
    storeApprovalActionRequest?: StoreApprovalActionRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/approvals/requests/${approval}/actions`, storeApprovalActionRequest
    ] as const;
    }


export const getApprovalsRequestsActionsQueryOptions = <TData = Awaited<ReturnType<typeof approvalsRequestsActions>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsRequestsActionsQueryKey(approval,storeApprovalActionRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsRequestsActions>>> = ({ signal }) => approvalsRequestsActions(approval,storeApprovalActionRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: approval !== null && approval !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsRequestsActionsQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsRequestsActions>>>
export type ApprovalsRequestsActionsQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useApprovalsRequestsActions<TData = Awaited<ReturnType<typeof approvalsRequestsActions>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsActions>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsActions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsActions<TData = Awaited<ReturnType<typeof approvalsRequestsActions>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsRequestsActions>>,
          TError,
          Awaited<ReturnType<typeof approvalsRequestsActions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsRequestsActions<TData = Awaited<ReturnType<typeof approvalsRequestsActions>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsRequestsActions<TData = Awaited<ReturnType<typeof approvalsRequestsActions>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 approval: string,
    storeApprovalActionRequest: StoreApprovalActionRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsRequestsActions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsRequestsActionsQueryOptions(approval,storeApprovalActionRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






