/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ProductsImportStore200,
  ProductsImportStore422,
  ProductsImportStoreBody
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type productsImportTemplateResponse200 = {
  data: string
  status: 200
}

export type productsImportTemplateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsImportTemplateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsImportTemplateResponseSuccess = (productsImportTemplateResponse200) & {
  headers: Headers;
};
export type productsImportTemplateResponseError = (productsImportTemplateResponse401 | productsImportTemplateResponse403) & {
  headers: Headers;
};

export type productsImportTemplateResponse = (productsImportTemplateResponseSuccess | productsImportTemplateResponseError)

export const getProductsImportTemplateUrl = () => {




  return `http://localhost:8000/api/v1/products/import/template`
}

export const productsImportTemplate = async ( options?: RequestInit): Promise<productsImportTemplateResponse> => {

  const res = await fetch(getProductsImportTemplateUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsImportTemplateResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as productsImportTemplateResponse
}





export const getProductsImportTemplateQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/products/import/template`
    ] as const;
    }


export const getProductsImportTemplateQueryOptions = <TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsImportTemplateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsImportTemplate>>> = ({ signal }) => productsImportTemplate({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsImportTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof productsImportTemplate>>>
export type ProductsImportTemplateQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useProductsImportTemplate<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsImportTemplate>>,
          TError,
          Awaited<ReturnType<typeof productsImportTemplate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportTemplate<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsImportTemplate>>,
          TError,
          Awaited<ReturnType<typeof productsImportTemplate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportTemplate<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsImportTemplate<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsImportTemplateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getProductsImportTemplateSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsImportTemplateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsImportTemplate>>> = ({ signal }) => productsImportTemplate({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsImportTemplateSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof productsImportTemplate>>>
export type ProductsImportTemplateSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useProductsImportTemplateSuspense<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportTemplateSuspense<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportTemplateSuspense<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsImportTemplateSuspense<TData = Awaited<ReturnType<typeof productsImportTemplate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsImportTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsImportTemplateSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsImportStoreResponse200 = {
  data: ProductsImportStore200
  status: 200
}

export type productsImportStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsImportStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsImportStoreResponse422 = {
  data: ProductsImportStore422
  status: 422
}

export type productsImportStoreResponseSuccess = (productsImportStoreResponse200) & {
  headers: Headers;
};
export type productsImportStoreResponseError = (productsImportStoreResponse401 | productsImportStoreResponse403 | productsImportStoreResponse422) & {
  headers: Headers;
};

export type productsImportStoreResponse = (productsImportStoreResponseSuccess | productsImportStoreResponseError)

export const getProductsImportStoreUrl = () => {




  return `http://localhost:8000/api/v1/products/import`
}

export const productsImportStore = async (productsImportStoreBody: ProductsImportStoreBody, options?: RequestInit): Promise<productsImportStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getProductsImportStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(productsImportStoreBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsImportStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsImportStoreResponse
}





export const getProductsImportStoreQueryKey = (productsImportStoreBody?: ProductsImportStoreBody,) => {
    return [
    'POST', `http://localhost:8000/api/v1/products/import`, productsImportStoreBody
    ] as const;
    }


export const getProductsImportStoreQueryOptions = <TData = Awaited<ReturnType<typeof productsImportStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422>(productsImportStoreBody: ProductsImportStoreBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsImportStoreQueryKey(productsImportStoreBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsImportStore>>> = ({ signal }) => productsImportStore(productsImportStoreBody, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsImportStoreQueryResult = NonNullable<Awaited<ReturnType<typeof productsImportStore>>>
export type ProductsImportStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422


export function useProductsImportStore<TData = Awaited<ReturnType<typeof productsImportStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422>(
 productsImportStoreBody: ProductsImportStoreBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsImportStore>>,
          TError,
          Awaited<ReturnType<typeof productsImportStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportStore<TData = Awaited<ReturnType<typeof productsImportStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422>(
 productsImportStoreBody: ProductsImportStoreBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsImportStore>>,
          TError,
          Awaited<ReturnType<typeof productsImportStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsImportStore<TData = Awaited<ReturnType<typeof productsImportStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422>(
 productsImportStoreBody: ProductsImportStoreBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsImportStore<TData = Awaited<ReturnType<typeof productsImportStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ProductsImportStore422>(
 productsImportStoreBody: ProductsImportStoreBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsImportStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsImportStoreQueryOptions(productsImportStoreBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






