/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StoreTelegramMessageRequest,
  TelegramMessagesIndex200,
  TelegramMessagesIndexParams,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type telegramMessagesIndexResponse200 = {
  data: TelegramMessagesIndex200
  status: 200
}

export type telegramMessagesIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramMessagesIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramMessagesIndexResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramMessagesIndexResponseSuccess = (telegramMessagesIndexResponse200) & {
  headers: Headers;
};
export type telegramMessagesIndexResponseError = (telegramMessagesIndexResponse401 | telegramMessagesIndexResponse403 | telegramMessagesIndexResponse422) & {
  headers: Headers;
};

export type telegramMessagesIndexResponse = (telegramMessagesIndexResponseSuccess | telegramMessagesIndexResponseError)

export const getTelegramMessagesIndexUrl = (params: TelegramMessagesIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/messages?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/messages`
}

export const telegramMessagesIndex = async (params: TelegramMessagesIndexParams, options?: RequestInit): Promise<telegramMessagesIndexResponse> => {

  const res = await fetch(getTelegramMessagesIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramMessagesIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramMessagesIndexResponse
}





export const getTelegramMessagesIndexQueryKey = (params?: TelegramMessagesIndexParams,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getTelegramMessagesIndexQueryOptions = <TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params: TelegramMessagesIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramMessagesIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramMessagesIndex>>> = ({ signal }) => telegramMessagesIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramMessagesIndexQueryResult = NonNullable<Awaited<ReturnType<typeof telegramMessagesIndex>>>
export type TelegramMessagesIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useTelegramMessagesIndex<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramMessagesIndex>>,
          TError,
          Awaited<ReturnType<typeof telegramMessagesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesIndex<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramMessagesIndex>>,
          TError,
          Awaited<ReturnType<typeof telegramMessagesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesIndex<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramMessagesIndex<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramMessagesIndexQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTelegramMessagesIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(params: TelegramMessagesIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramMessagesIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramMessagesIndex>>> = ({ signal }) => telegramMessagesIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramMessagesIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof telegramMessagesIndex>>>
export type TelegramMessagesIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useTelegramMessagesIndexSuspense<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesIndexSuspense<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesIndexSuspense<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramMessagesIndexSuspense<TData = Awaited<ReturnType<typeof telegramMessagesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 params: TelegramMessagesIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramMessagesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramMessagesIndexSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramMessagesStoreResponse200 = {
  data: string
  status: 200
}

export type telegramMessagesStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramMessagesStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramMessagesStoreResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramMessagesStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramMessagesStoreResponseSuccess = (telegramMessagesStoreResponse200) & {
  headers: Headers;
};
export type telegramMessagesStoreResponseError = (telegramMessagesStoreResponse401 | telegramMessagesStoreResponse403 | telegramMessagesStoreResponse404 | telegramMessagesStoreResponse422) & {
  headers: Headers;
};

export type telegramMessagesStoreResponse = (telegramMessagesStoreResponseSuccess | telegramMessagesStoreResponseError)

export const getTelegramMessagesStoreUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/messages`
}

export const telegramMessagesStore = async (storeTelegramMessageRequest: StoreTelegramMessageRequest, options?: RequestInit): Promise<telegramMessagesStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getTelegramMessagesStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeTelegramMessageRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramMessagesStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramMessagesStoreResponse
}





export const getTelegramMessagesStoreQueryKey = (storeTelegramMessageRequest?: StoreTelegramMessageRequest,) => {
    return [
    'POST', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/messages`, storeTelegramMessageRequest
    ] as const;
    }


export const getTelegramMessagesStoreQueryOptions = <TData = Awaited<ReturnType<typeof telegramMessagesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(storeTelegramMessageRequest: StoreTelegramMessageRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramMessagesStoreQueryKey(storeTelegramMessageRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramMessagesStore>>> = ({ signal }) => telegramMessagesStore(storeTelegramMessageRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramMessagesStoreQueryResult = NonNullable<Awaited<ReturnType<typeof telegramMessagesStore>>>
export type TelegramMessagesStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useTelegramMessagesStore<TData = Awaited<ReturnType<typeof telegramMessagesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 storeTelegramMessageRequest: StoreTelegramMessageRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramMessagesStore>>,
          TError,
          Awaited<ReturnType<typeof telegramMessagesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesStore<TData = Awaited<ReturnType<typeof telegramMessagesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 storeTelegramMessageRequest: StoreTelegramMessageRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramMessagesStore>>,
          TError,
          Awaited<ReturnType<typeof telegramMessagesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramMessagesStore<TData = Awaited<ReturnType<typeof telegramMessagesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 storeTelegramMessageRequest: StoreTelegramMessageRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramMessagesStore<TData = Awaited<ReturnType<typeof telegramMessagesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 storeTelegramMessageRequest: StoreTelegramMessageRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramMessagesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramMessagesStoreQueryOptions(storeTelegramMessageRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






