/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  RolesRolesDestroy200,
  RolesRolesIndex200,
  RolesRolesShow200,
  RolesRolesStore201,
  RolesRolesUpdate200,
  StoreRoleRequest,
  UpdateRoleRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rolesRolesIndexResponse200 = {
  data: RolesRolesIndex200
  status: 200
}

export type rolesRolesIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type rolesRolesIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type rolesRolesIndexResponseSuccess = (rolesRolesIndexResponse200) & {
  headers: Headers;
};
export type rolesRolesIndexResponseError = (rolesRolesIndexResponse401 | rolesRolesIndexResponse403) & {
  headers: Headers;
};

export type rolesRolesIndexResponse = (rolesRolesIndexResponseSuccess | rolesRolesIndexResponseError)

export const getRolesRolesIndexUrl = () => {




  return `http://localhost:8000/api/v1/roles`
}

export const rolesRolesIndex = async ( options?: RequestInit): Promise<rolesRolesIndexResponse> => {

  const res = await fetch(getRolesRolesIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolesRolesIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolesRolesIndexResponse
}





export const getRolesRolesIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/roles`
    ] as const;
    }


export const getRolesRolesIndexQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesIndex>>> = ({ signal }) => rolesRolesIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesIndexQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesIndex>>>
export type RolesRolesIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useRolesRolesIndex<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesIndex>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesIndex<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesIndex>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesIndex<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesIndex<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getRolesRolesIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesIndex>>> = ({ signal }) => rolesRolesIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesIndex>>>
export type RolesRolesIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useRolesRolesIndexSuspense<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesIndexSuspense<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesIndexSuspense<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesIndexSuspense<TData = Awaited<ReturnType<typeof rolesRolesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type rolesRolesStoreResponse201 = {
  data: RolesRolesStore201
  status: 201
}

export type rolesRolesStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type rolesRolesStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type rolesRolesStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type rolesRolesStoreResponseSuccess = (rolesRolesStoreResponse201) & {
  headers: Headers;
};
export type rolesRolesStoreResponseError = (rolesRolesStoreResponse401 | rolesRolesStoreResponse403 | rolesRolesStoreResponse422) & {
  headers: Headers;
};

export type rolesRolesStoreResponse = (rolesRolesStoreResponseSuccess | rolesRolesStoreResponseError)

export const getRolesRolesStoreUrl = () => {




  return `http://localhost:8000/api/v1/roles`
}

export const rolesRolesStore = async (storeRoleRequest: StoreRoleRequest, options?: RequestInit): Promise<rolesRolesStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getRolesRolesStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolesRolesStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolesRolesStoreResponse
}





export const getRolesRolesStoreQueryKey = (storeRoleRequest?: StoreRoleRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/roles`, storeRoleRequest
    ] as const;
    }


export const getRolesRolesStoreQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(storeRoleRequest: StoreRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesStoreQueryKey(storeRoleRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesStore>>> = ({ signal }) => rolesRolesStore(storeRoleRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesStoreQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesStore>>>
export type RolesRolesStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useRolesRolesStore<TData = Awaited<ReturnType<typeof rolesRolesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeRoleRequest: StoreRoleRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesStore>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesStore<TData = Awaited<ReturnType<typeof rolesRolesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeRoleRequest: StoreRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesStore>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesStore<TData = Awaited<ReturnType<typeof rolesRolesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeRoleRequest: StoreRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesStore<TData = Awaited<ReturnType<typeof rolesRolesStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeRoleRequest: StoreRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesStoreQueryOptions(storeRoleRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type rolesRolesShowResponse200 = {
  data: RolesRolesShow200
  status: 200
}

export type rolesRolesShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type rolesRolesShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type rolesRolesShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type rolesRolesShowResponseSuccess = (rolesRolesShowResponse200) & {
  headers: Headers;
};
export type rolesRolesShowResponseError = (rolesRolesShowResponse401 | rolesRolesShowResponse403 | rolesRolesShowResponse404) & {
  headers: Headers;
};

export type rolesRolesShowResponse = (rolesRolesShowResponseSuccess | rolesRolesShowResponseError)

export const getRolesRolesShowUrl = (role: number,) => {




  return `http://localhost:8000/api/v1/roles/${role}`
}

export const rolesRolesShow = async (role: number, options?: RequestInit): Promise<rolesRolesShowResponse> => {

  const res = await fetch(getRolesRolesShowUrl(role),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolesRolesShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolesRolesShowResponse
}





export const getRolesRolesShowQueryKey = (role: number,) => {
    return [
    `http://localhost:8000/api/v1/roles/${role}`
    ] as const;
    }


export const getRolesRolesShowQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesShowQueryKey(role);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesShow>>> = ({ signal }) => rolesRolesShow(role, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: role !== null && role !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesShowQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesShow>>>
export type RolesRolesShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useRolesRolesShow<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesShow>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesShow<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesShow>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesShow<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesShow<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesShowQueryOptions(role,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getRolesRolesShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(role: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesShowQueryKey(role);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesShow>>> = ({ signal }) => rolesRolesShow(role, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesShow>>>
export type RolesRolesShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useRolesRolesShowSuspense<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesShowSuspense<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesShowSuspense<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesShowSuspense<TData = Awaited<ReturnType<typeof rolesRolesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof rolesRolesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesShowSuspenseQueryOptions(role,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type rolesRolesUpdateResponse200 = {
  data: RolesRolesUpdate200
  status: 200
}

export type rolesRolesUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type rolesRolesUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type rolesRolesUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type rolesRolesUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type rolesRolesUpdateResponseSuccess = (rolesRolesUpdateResponse200) & {
  headers: Headers;
};
export type rolesRolesUpdateResponseError = (rolesRolesUpdateResponse401 | rolesRolesUpdateResponse403 | rolesRolesUpdateResponse404 | rolesRolesUpdateResponse422) & {
  headers: Headers;
};

export type rolesRolesUpdateResponse = (rolesRolesUpdateResponseSuccess | rolesRolesUpdateResponseError)

export const getRolesRolesUpdateUrl = (role: number,) => {




  return `http://localhost:8000/api/v1/roles/${role}`
}

export const rolesRolesUpdate = async (role: number,
    updateRoleRequest?: UpdateRoleRequest, options?: RequestInit): Promise<rolesRolesUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getRolesRolesUpdateUrl(role),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolesRolesUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolesRolesUpdateResponse
}





export const getRolesRolesUpdateQueryKey = (role: number,
    updateRoleRequest?: UpdateRoleRequest,) => {
    return [
    'PUT', `http://localhost:8000/api/v1/roles/${role}`, updateRoleRequest
    ] as const;
    }


export const getRolesRolesUpdateQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(role: number,
    updateRoleRequest?: UpdateRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesUpdateQueryKey(role,updateRoleRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesUpdate>>> = ({ signal }) => rolesRolesUpdate(role,updateRoleRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: role !== null && role !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesUpdate>>>
export type RolesRolesUpdateQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useRolesRolesUpdate<TData = Awaited<ReturnType<typeof rolesRolesUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 role: number,
    updateRoleRequest: undefined |  UpdateRoleRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesUpdate>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesUpdate<TData = Awaited<ReturnType<typeof rolesRolesUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 role: number,
    updateRoleRequest?: UpdateRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesUpdate>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesUpdate<TData = Awaited<ReturnType<typeof rolesRolesUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 role: number,
    updateRoleRequest?: UpdateRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesUpdate<TData = Awaited<ReturnType<typeof rolesRolesUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 role: number,
    updateRoleRequest?: UpdateRoleRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesUpdateQueryOptions(role,updateRoleRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type rolesRolesDestroyResponse200 = {
  data: RolesRolesDestroy200
  status: 200
}

export type rolesRolesDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type rolesRolesDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type rolesRolesDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type rolesRolesDestroyResponseSuccess = (rolesRolesDestroyResponse200) & {
  headers: Headers;
};
export type rolesRolesDestroyResponseError = (rolesRolesDestroyResponse401 | rolesRolesDestroyResponse403 | rolesRolesDestroyResponse404) & {
  headers: Headers;
};

export type rolesRolesDestroyResponse = (rolesRolesDestroyResponseSuccess | rolesRolesDestroyResponseError)

export const getRolesRolesDestroyUrl = (role: number,) => {




  return `http://localhost:8000/api/v1/roles/${role}`
}

export const rolesRolesDestroy = async (role: number, options?: RequestInit): Promise<rolesRolesDestroyResponse> => {

  const res = await fetch(getRolesRolesDestroyUrl(role),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolesRolesDestroyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolesRolesDestroyResponse
}





export const getRolesRolesDestroyQueryKey = (role: number,) => {
    return [
    'DELETE', `http://localhost:8000/api/v1/roles/${role}`
    ] as const;
    }


export const getRolesRolesDestroyQueryOptions = <TData = Awaited<ReturnType<typeof rolesRolesDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolesRolesDestroyQueryKey(role);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolesRolesDestroy>>> = ({ signal }) => rolesRolesDestroy(role, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: role !== null && role !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolesRolesDestroyQueryResult = NonNullable<Awaited<ReturnType<typeof rolesRolesDestroy>>>
export type RolesRolesDestroyQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useRolesRolesDestroy<TData = Awaited<ReturnType<typeof rolesRolesDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesDestroy>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesDestroy<TData = Awaited<ReturnType<typeof rolesRolesDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolesRolesDestroy>>,
          TError,
          Awaited<ReturnType<typeof rolesRolesDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolesRolesDestroy<TData = Awaited<ReturnType<typeof rolesRolesDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRolesRolesDestroy<TData = Awaited<ReturnType<typeof rolesRolesDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 role: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolesRolesDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolesRolesDestroyQueryOptions(role,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






