/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  ProductsCategoriesDestroy200,
  ProductsCategoriesIndex200,
  ProductsCategoriesShow200,
  ProductsCategoriesStore201,
  ProductsCategoriesTree200,
  StoreProductCategoryRequest,
  UpdateProductCategoryRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type productsCategoriesTreeResponse200 = {
  data: ProductsCategoriesTree200
  status: 200
}

export type productsCategoriesTreeResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesTreeResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsCategoriesTreeResponseSuccess = (productsCategoriesTreeResponse200) & {
  headers: Headers;
};
export type productsCategoriesTreeResponseError = (productsCategoriesTreeResponse401 | productsCategoriesTreeResponse403) & {
  headers: Headers;
};

export type productsCategoriesTreeResponse = (productsCategoriesTreeResponseSuccess | productsCategoriesTreeResponseError)

export const getProductsCategoriesTreeUrl = () => {




  return `http://localhost:8000/api/v1/products/categories/tree`
}

export const productsCategoriesTree = async ( options?: RequestInit): Promise<productsCategoriesTreeResponse> => {

  const res = await fetch(getProductsCategoriesTreeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesTreeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesTreeResponse
}





export const getProductsCategoriesTreeQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/products/categories/tree`
    ] as const;
    }


export const getProductsCategoriesTreeQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesTreeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesTree>>> = ({ signal }) => productsCategoriesTree({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesTreeQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesTree>>>
export type ProductsCategoriesTreeQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useProductsCategoriesTree<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesTree>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesTree>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesTree<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesTree>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesTree>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesTree<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesTree<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesTreeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getProductsCategoriesTreeSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesTreeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesTree>>> = ({ signal }) => productsCategoriesTree({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesTreeSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesTree>>>
export type ProductsCategoriesTreeSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useProductsCategoriesTreeSuspense<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesTreeSuspense<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesTreeSuspense<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesTreeSuspense<TData = Awaited<ReturnType<typeof productsCategoriesTree>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesTreeSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsCategoriesIndexResponse200 = {
  data: ProductsCategoriesIndex200
  status: 200
}

export type productsCategoriesIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesIndexResponseSuccess = (productsCategoriesIndexResponse200) & {
  headers: Headers;
};
export type productsCategoriesIndexResponseError = (productsCategoriesIndexResponse401) & {
  headers: Headers;
};

export type productsCategoriesIndexResponse = (productsCategoriesIndexResponseSuccess | productsCategoriesIndexResponseError)

export const getProductsCategoriesIndexUrl = () => {




  return `http://localhost:8000/api/v1/products/categories`
}

export const productsCategoriesIndex = async ( options?: RequestInit): Promise<productsCategoriesIndexResponse> => {

  const res = await fetch(getProductsCategoriesIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesIndexResponse
}





export const getProductsCategoriesIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/products/categories`
    ] as const;
    }


export const getProductsCategoriesIndexQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesIndex>>> = ({ signal }) => productsCategoriesIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesIndexQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesIndex>>>
export type ProductsCategoriesIndexQueryError = AuthenticationExceptionResponse


export function useProductsCategoriesIndex<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesIndex>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesIndex<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesIndex>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesIndex<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesIndex<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getProductsCategoriesIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesIndex>>> = ({ signal }) => productsCategoriesIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesIndex>>>
export type ProductsCategoriesIndexSuspenseQueryError = AuthenticationExceptionResponse


export function useProductsCategoriesIndexSuspense<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesIndexSuspense<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesIndexSuspense<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesIndexSuspense<TData = Awaited<ReturnType<typeof productsCategoriesIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsCategoriesStoreResponse201 = {
  data: ProductsCategoriesStore201
  status: 201
}

export type productsCategoriesStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type productsCategoriesStoreResponseSuccess = (productsCategoriesStoreResponse201) & {
  headers: Headers;
};
export type productsCategoriesStoreResponseError = (productsCategoriesStoreResponse401 | productsCategoriesStoreResponse422) & {
  headers: Headers;
};

export type productsCategoriesStoreResponse = (productsCategoriesStoreResponseSuccess | productsCategoriesStoreResponseError)

export const getProductsCategoriesStoreUrl = () => {




  return `http://localhost:8000/api/v1/products/categories`
}

export const productsCategoriesStore = async (storeProductCategoryRequest: StoreProductCategoryRequest, options?: RequestInit): Promise<productsCategoriesStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getProductsCategoriesStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeProductCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesStoreResponse
}





export const getProductsCategoriesStoreQueryKey = (storeProductCategoryRequest?: StoreProductCategoryRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/products/categories`, storeProductCategoryRequest
    ] as const;
    }


export const getProductsCategoriesStoreQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesStore>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(storeProductCategoryRequest: StoreProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesStoreQueryKey(storeProductCategoryRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesStore>>> = ({ signal }) => productsCategoriesStore(storeProductCategoryRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesStoreQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesStore>>>
export type ProductsCategoriesStoreQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse


export function useProductsCategoriesStore<TData = Awaited<ReturnType<typeof productsCategoriesStore>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 storeProductCategoryRequest: StoreProductCategoryRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesStore>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesStore<TData = Awaited<ReturnType<typeof productsCategoriesStore>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 storeProductCategoryRequest: StoreProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesStore>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesStore<TData = Awaited<ReturnType<typeof productsCategoriesStore>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 storeProductCategoryRequest: StoreProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesStore<TData = Awaited<ReturnType<typeof productsCategoriesStore>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse>(
 storeProductCategoryRequest: StoreProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesStoreQueryOptions(storeProductCategoryRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsCategoriesShowResponse200 = {
  data: ProductsCategoriesShow200
  status: 200
}

export type productsCategoriesShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsCategoriesShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type productsCategoriesShowResponseSuccess = (productsCategoriesShowResponse200) & {
  headers: Headers;
};
export type productsCategoriesShowResponseError = (productsCategoriesShowResponse401 | productsCategoriesShowResponse403 | productsCategoriesShowResponse404) & {
  headers: Headers;
};

export type productsCategoriesShowResponse = (productsCategoriesShowResponseSuccess | productsCategoriesShowResponseError)

export const getProductsCategoriesShowUrl = (category: string,) => {




  return `http://localhost:8000/api/v1/products/categories/${category}`
}

export const productsCategoriesShow = async (category: string, options?: RequestInit): Promise<productsCategoriesShowResponse> => {

  const res = await fetch(getProductsCategoriesShowUrl(category),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesShowResponse
}





export const getProductsCategoriesShowQueryKey = (category: string,) => {
    return [
    `http://localhost:8000/api/v1/products/categories/${category}`
    ] as const;
    }


export const getProductsCategoriesShowQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesShowQueryKey(category);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesShow>>> = ({ signal }) => productsCategoriesShow(category, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: category !== null && category !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesShowQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesShow>>>
export type ProductsCategoriesShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useProductsCategoriesShow<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesShow>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesShow<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesShow>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesShow<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesShow<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesShowQueryOptions(category,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getProductsCategoriesShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(category: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesShowQueryKey(category);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesShow>>> = ({ signal }) => productsCategoriesShow(category, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesShow>>>
export type ProductsCategoriesShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useProductsCategoriesShowSuspense<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesShowSuspense<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesShowSuspense<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesShowSuspense<TData = Awaited<ReturnType<typeof productsCategoriesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof productsCategoriesShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesShowSuspenseQueryOptions(category,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsCategoriesUpdateResponse200 = {
  data: unknown
  status: 200
}

export type productsCategoriesUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type productsCategoriesUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type productsCategoriesUpdateResponseSuccess = (productsCategoriesUpdateResponse200) & {
  headers: Headers;
};
export type productsCategoriesUpdateResponseError = (productsCategoriesUpdateResponse401 | productsCategoriesUpdateResponse404 | productsCategoriesUpdateResponse422) & {
  headers: Headers;
};

export type productsCategoriesUpdateResponse = (productsCategoriesUpdateResponseSuccess | productsCategoriesUpdateResponseError)

export const getProductsCategoriesUpdateUrl = (category: string,) => {




  return `http://localhost:8000/api/v1/products/categories/${category}`
}

export const productsCategoriesUpdate = async (category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest, options?: RequestInit): Promise<productsCategoriesUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getProductsCategoriesUpdateUrl(category),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateProductCategoryRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesUpdateResponse
}





export const getProductsCategoriesUpdateQueryKey = (category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest,) => {
    return [
    'PUT', `http://localhost:8000/api/v1/products/categories/${category}`, updateProductCategoryRequest
    ] as const;
    }


export const getProductsCategoriesUpdateQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesUpdateQueryKey(category,updateProductCategoryRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesUpdate>>> = ({ signal }) => productsCategoriesUpdate(category,updateProductCategoryRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: category !== null && category !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesUpdate>>>
export type ProductsCategoriesUpdateQueryError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useProductsCategoriesUpdate<TData = Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 category: string,
    updateProductCategoryRequest: undefined |  UpdateProductCategoryRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesUpdate>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesUpdate<TData = Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesUpdate>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesUpdate<TData = Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesUpdate<TData = Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 category: string,
    updateProductCategoryRequest?: UpdateProductCategoryRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesUpdateQueryOptions(category,updateProductCategoryRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type productsCategoriesDestroyResponse200 = {
  data: ProductsCategoriesDestroy200
  status: 200
}

export type productsCategoriesDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsCategoriesDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type productsCategoriesDestroyResponseSuccess = (productsCategoriesDestroyResponse200) & {
  headers: Headers;
};
export type productsCategoriesDestroyResponseError = (productsCategoriesDestroyResponse401 | productsCategoriesDestroyResponse404) & {
  headers: Headers;
};

export type productsCategoriesDestroyResponse = (productsCategoriesDestroyResponseSuccess | productsCategoriesDestroyResponseError)

export const getProductsCategoriesDestroyUrl = (category: string,) => {




  return `http://localhost:8000/api/v1/products/categories/${category}`
}

export const productsCategoriesDestroy = async (category: string, options?: RequestInit): Promise<productsCategoriesDestroyResponse> => {

  const res = await fetch(getProductsCategoriesDestroyUrl(category),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: productsCategoriesDestroyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsCategoriesDestroyResponse
}





export const getProductsCategoriesDestroyQueryKey = (category: string,) => {
    return [
    'DELETE', `http://localhost:8000/api/v1/products/categories/${category}`
    ] as const;
    }


export const getProductsCategoriesDestroyQueryOptions = <TData = Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsCategoriesDestroyQueryKey(category);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsCategoriesDestroy>>> = ({ signal }) => productsCategoriesDestroy(category, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: category !== null && category !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsCategoriesDestroyQueryResult = NonNullable<Awaited<ReturnType<typeof productsCategoriesDestroy>>>
export type ProductsCategoriesDestroyQueryError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse


export function useProductsCategoriesDestroy<TData = Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesDestroy>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesDestroy<TData = Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsCategoriesDestroy>>,
          TError,
          Awaited<ReturnType<typeof productsCategoriesDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsCategoriesDestroy<TData = Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProductsCategoriesDestroy<TData = Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 category: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsCategoriesDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsCategoriesDestroyQueryOptions(category,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






