/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ApprovalsFlowsDestroy200,
  ApprovalsFlowsIndex200,
  ApprovalsFlowsShow200,
  ApprovalsFlowsStore201,
  ApprovalsFlowsUpdate200,
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StoreApprovalFlowRequest,
  UpdateApprovalFlowRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type approvalsFlowsIndexResponse200 = {
  data: ApprovalsFlowsIndex200
  status: 200
}

export type approvalsFlowsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsFlowsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsFlowsIndexResponseSuccess = (approvalsFlowsIndexResponse200) & {
  headers: Headers;
};
export type approvalsFlowsIndexResponseError = (approvalsFlowsIndexResponse401 | approvalsFlowsIndexResponse403) & {
  headers: Headers;
};

export type approvalsFlowsIndexResponse = (approvalsFlowsIndexResponseSuccess | approvalsFlowsIndexResponseError)

export const getApprovalsFlowsIndexUrl = () => {




  return `http://localhost:8000/api/v1/approvals/flows`
}

export const approvalsFlowsIndex = async ( options?: RequestInit): Promise<approvalsFlowsIndexResponse> => {

  const res = await fetch(getApprovalsFlowsIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsFlowsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsFlowsIndexResponse
}





export const getApprovalsFlowsIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/approvals/flows`
    ] as const;
    }


export const getApprovalsFlowsIndexQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsIndex>>> = ({ signal }) => approvalsFlowsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsIndex>>>
export type ApprovalsFlowsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useApprovalsFlowsIndex<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsIndex<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsIndex<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsIndex<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsFlowsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsIndex>>> = ({ signal }) => approvalsFlowsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsIndex>>>
export type ApprovalsFlowsIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useApprovalsFlowsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsFlowsStoreResponse201 = {
  data: ApprovalsFlowsStore201
  status: 201
}

export type approvalsFlowsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsFlowsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsFlowsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsFlowsStoreResponseSuccess = (approvalsFlowsStoreResponse201) & {
  headers: Headers;
};
export type approvalsFlowsStoreResponseError = (approvalsFlowsStoreResponse401 | approvalsFlowsStoreResponse403 | approvalsFlowsStoreResponse422) & {
  headers: Headers;
};

export type approvalsFlowsStoreResponse = (approvalsFlowsStoreResponseSuccess | approvalsFlowsStoreResponseError)

export const getApprovalsFlowsStoreUrl = () => {




  return `http://localhost:8000/api/v1/approvals/flows`
}

export const approvalsFlowsStore = async (storeApprovalFlowRequest: StoreApprovalFlowRequest, options?: RequestInit): Promise<approvalsFlowsStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getApprovalsFlowsStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeApprovalFlowRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsFlowsStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsFlowsStoreResponse
}





export const getApprovalsFlowsStoreQueryKey = (storeApprovalFlowRequest?: StoreApprovalFlowRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/approvals/flows`, storeApprovalFlowRequest
    ] as const;
    }


export const getApprovalsFlowsStoreQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(storeApprovalFlowRequest: StoreApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsStoreQueryKey(storeApprovalFlowRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsStore>>> = ({ signal }) => approvalsFlowsStore(storeApprovalFlowRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsStoreQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsStore>>>
export type ApprovalsFlowsStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useApprovalsFlowsStore<TData = Awaited<ReturnType<typeof approvalsFlowsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalFlowRequest: StoreApprovalFlowRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsStore>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsStore<TData = Awaited<ReturnType<typeof approvalsFlowsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalFlowRequest: StoreApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsStore>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsStore<TData = Awaited<ReturnType<typeof approvalsFlowsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalFlowRequest: StoreApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsStore<TData = Awaited<ReturnType<typeof approvalsFlowsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeApprovalFlowRequest: StoreApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsStoreQueryOptions(storeApprovalFlowRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsFlowsShowResponse200 = {
  data: ApprovalsFlowsShow200
  status: 200
}

export type approvalsFlowsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsFlowsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsFlowsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type approvalsFlowsShowResponseSuccess = (approvalsFlowsShowResponse200) & {
  headers: Headers;
};
export type approvalsFlowsShowResponseError = (approvalsFlowsShowResponse401 | approvalsFlowsShowResponse403 | approvalsFlowsShowResponse404) & {
  headers: Headers;
};

export type approvalsFlowsShowResponse = (approvalsFlowsShowResponseSuccess | approvalsFlowsShowResponseError)

export const getApprovalsFlowsShowUrl = (flow: string,) => {




  return `http://localhost:8000/api/v1/approvals/flows/${flow}`
}

export const approvalsFlowsShow = async (flow: string, options?: RequestInit): Promise<approvalsFlowsShowResponse> => {

  const res = await fetch(getApprovalsFlowsShowUrl(flow),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsFlowsShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsFlowsShowResponse
}





export const getApprovalsFlowsShowQueryKey = (flow: string,) => {
    return [
    `http://localhost:8000/api/v1/approvals/flows/${flow}`
    ] as const;
    }


export const getApprovalsFlowsShowQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsShowQueryKey(flow);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsShow>>> = ({ signal }) => approvalsFlowsShow(flow, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: flow !== null && flow !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsShowQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsShow>>>
export type ApprovalsFlowsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useApprovalsFlowsShow<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsShow>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsShow<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsShow>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsShow<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsShow<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsShowQueryOptions(flow,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsFlowsShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(flow: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsShowQueryKey(flow);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsShow>>> = ({ signal }) => approvalsFlowsShow(flow, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsShow>>>
export type ApprovalsFlowsShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useApprovalsFlowsShowSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsShowSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsShowSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsShowSuspense<TData = Awaited<ReturnType<typeof approvalsFlowsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsShowSuspenseQueryOptions(flow,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsFlowsUpdateResponse200 = {
  data: ApprovalsFlowsUpdate200
  status: 200
}

export type approvalsFlowsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsFlowsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsFlowsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type approvalsFlowsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type approvalsFlowsUpdateResponseSuccess = (approvalsFlowsUpdateResponse200) & {
  headers: Headers;
};
export type approvalsFlowsUpdateResponseError = (approvalsFlowsUpdateResponse401 | approvalsFlowsUpdateResponse403 | approvalsFlowsUpdateResponse404 | approvalsFlowsUpdateResponse422) & {
  headers: Headers;
};

export type approvalsFlowsUpdateResponse = (approvalsFlowsUpdateResponseSuccess | approvalsFlowsUpdateResponseError)

export const getApprovalsFlowsUpdateUrl = (flow: string,) => {




  return `http://localhost:8000/api/v1/approvals/flows/${flow}`
}

export const approvalsFlowsUpdate = async (flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest, options?: RequestInit): Promise<approvalsFlowsUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getApprovalsFlowsUpdateUrl(flow),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateApprovalFlowRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsFlowsUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsFlowsUpdateResponse
}





export const getApprovalsFlowsUpdateQueryKey = (flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest,) => {
    return [
    'PUT', `http://localhost:8000/api/v1/approvals/flows/${flow}`, updateApprovalFlowRequest
    ] as const;
    }


export const getApprovalsFlowsUpdateQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsUpdateQueryKey(flow,updateApprovalFlowRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsUpdate>>> = ({ signal }) => approvalsFlowsUpdate(flow,updateApprovalFlowRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: flow !== null && flow !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsUpdate>>>
export type ApprovalsFlowsUpdateQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useApprovalsFlowsUpdate<TData = Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 flow: string,
    updateApprovalFlowRequest: undefined |  UpdateApprovalFlowRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsUpdate>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsUpdate<TData = Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsUpdate>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsUpdate<TData = Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsUpdate<TData = Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 flow: string,
    updateApprovalFlowRequest?: UpdateApprovalFlowRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsUpdateQueryOptions(flow,updateApprovalFlowRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type approvalsFlowsDestroyResponse200 = {
  data: ApprovalsFlowsDestroy200
  status: 200
}

export type approvalsFlowsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsFlowsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsFlowsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type approvalsFlowsDestroyResponseSuccess = (approvalsFlowsDestroyResponse200) & {
  headers: Headers;
};
export type approvalsFlowsDestroyResponseError = (approvalsFlowsDestroyResponse401 | approvalsFlowsDestroyResponse403 | approvalsFlowsDestroyResponse404) & {
  headers: Headers;
};

export type approvalsFlowsDestroyResponse = (approvalsFlowsDestroyResponseSuccess | approvalsFlowsDestroyResponseError)

export const getApprovalsFlowsDestroyUrl = (flow: string,) => {




  return `http://localhost:8000/api/v1/approvals/flows/${flow}`
}

export const approvalsFlowsDestroy = async (flow: string, options?: RequestInit): Promise<approvalsFlowsDestroyResponse> => {

  const res = await fetch(getApprovalsFlowsDestroyUrl(flow),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsFlowsDestroyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsFlowsDestroyResponse
}





export const getApprovalsFlowsDestroyQueryKey = (flow: string,) => {
    return [
    'DELETE', `http://localhost:8000/api/v1/approvals/flows/${flow}`
    ] as const;
    }


export const getApprovalsFlowsDestroyQueryOptions = <TData = Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsFlowsDestroyQueryKey(flow);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsFlowsDestroy>>> = ({ signal }) => approvalsFlowsDestroy(flow, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: flow !== null && flow !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsFlowsDestroyQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsFlowsDestroy>>>
export type ApprovalsFlowsDestroyQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useApprovalsFlowsDestroy<TData = Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsDestroy>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsDestroy<TData = Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsFlowsDestroy>>,
          TError,
          Awaited<ReturnType<typeof approvalsFlowsDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsFlowsDestroy<TData = Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApprovalsFlowsDestroy<TData = Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 flow: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsFlowsDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsFlowsDestroyQueryOptions(flow,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






