/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  EpurchaseVendorsInfo200,
  EpurchaseVendorsInfo502,
  EpurchaseVendorsSearch200,
  EpurchaseVendorsSearch502,
  EpurchaseVendorsSearchParams,
  ShowEPurchaseVendorInfoRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type epurchaseVendorsSearchResponse200 = {
  data: EpurchaseVendorsSearch200
  status: 200
}

export type epurchaseVendorsSearchResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchaseVendorsSearchResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type epurchaseVendorsSearchResponse502 = {
  data: EpurchaseVendorsSearch502
  status: 502
}

export type epurchaseVendorsSearchResponseSuccess = (epurchaseVendorsSearchResponse200) & {
  headers: Headers;
};
export type epurchaseVendorsSearchResponseError = (epurchaseVendorsSearchResponse401 | epurchaseVendorsSearchResponse422 | epurchaseVendorsSearchResponse502) & {
  headers: Headers;
};

export type epurchaseVendorsSearchResponse = (epurchaseVendorsSearchResponseSuccess | epurchaseVendorsSearchResponseError)

export const getEpurchaseVendorsSearchUrl = (params?: EpurchaseVendorsSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/api/v1/epurchase/vendor-search?${stringifiedParams}` : `http://localhost:8000/api/v1/epurchase/vendor-search`
}

/**
 * @summary Read-only proxy of upstream /api/po/getVentors (autocomplete search)
 */
export const epurchaseVendorsSearch = async (params?: EpurchaseVendorsSearchParams, options?: RequestInit): Promise<epurchaseVendorsSearchResponse> => {

  const res = await fetch(getEpurchaseVendorsSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchaseVendorsSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchaseVendorsSearchResponse
}





export const getEpurchaseVendorsSearchQueryKey = (params?: EpurchaseVendorsSearchParams,) => {
    return [
    `http://localhost:8000/api/v1/epurchase/vendor-search`, ...(params ? [params] : [])
    ] as const;
    }


export const getEpurchaseVendorsSearchQueryOptions = <TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchaseVendorsSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchaseVendorsSearch>>> = ({ signal }) => epurchaseVendorsSearch(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchaseVendorsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof epurchaseVendorsSearch>>>
export type EpurchaseVendorsSearchQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502


export function useEpurchaseVendorsSearch<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params: undefined |  EpurchaseVendorsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchaseVendorsSearch>>,
          TError,
          Awaited<ReturnType<typeof epurchaseVendorsSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsSearch<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchaseVendorsSearch>>,
          TError,
          Awaited<ReturnType<typeof epurchaseVendorsSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsSearch<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of upstream /api/po/getVentors (autocomplete search)
 */

export function useEpurchaseVendorsSearch<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchaseVendorsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEpurchaseVendorsSearchSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchaseVendorsSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchaseVendorsSearch>>> = ({ signal }) => epurchaseVendorsSearch(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchaseVendorsSearchSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof epurchaseVendorsSearch>>>
export type EpurchaseVendorsSearchSuspenseQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502


export function useEpurchaseVendorsSearchSuspense<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params: undefined |  EpurchaseVendorsSearchParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsSearchSuspense<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsSearchSuspense<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of upstream /api/po/getVentors (autocomplete search)
 */

export function useEpurchaseVendorsSearchSuspense<TData = Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsSearch502>(
 params?: EpurchaseVendorsSearchParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchaseVendorsSearchSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type epurchaseVendorsInfoResponse200 = {
  data: EpurchaseVendorsInfo200
  status: 200
}

export type epurchaseVendorsInfoResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchaseVendorsInfoResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type epurchaseVendorsInfoResponse502 = {
  data: EpurchaseVendorsInfo502
  status: 502
}

export type epurchaseVendorsInfoResponseSuccess = (epurchaseVendorsInfoResponse200) & {
  headers: Headers;
};
export type epurchaseVendorsInfoResponseError = (epurchaseVendorsInfoResponse401 | epurchaseVendorsInfoResponse422 | epurchaseVendorsInfoResponse502) & {
  headers: Headers;
};

export type epurchaseVendorsInfoResponse = (epurchaseVendorsInfoResponseSuccess | epurchaseVendorsInfoResponseError)

export const getEpurchaseVendorsInfoUrl = () => {




  return `http://localhost:8000/api/v1/epurchase/vendor-info`
}

/**
 * @summary Read-only proxy of upstream /api/po/getVendorInfo (full vendor profile)
 */
export const epurchaseVendorsInfo = async (showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options?: RequestInit): Promise<epurchaseVendorsInfoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getEpurchaseVendorsInfoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(showEPurchaseVendorInfoRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchaseVendorsInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchaseVendorsInfoResponse
}





export const getEpurchaseVendorsInfoQueryKey = (showEPurchaseVendorInfoRequest?: ShowEPurchaseVendorInfoRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/epurchase/vendor-info`, showEPurchaseVendorInfoRequest
    ] as const;
    }


export const getEpurchaseVendorsInfoQueryOptions = <TData = Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502>(showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchaseVendorsInfoQueryKey(showEPurchaseVendorInfoRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchaseVendorsInfo>>> = ({ signal }) => epurchaseVendorsInfo(showEPurchaseVendorInfoRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchaseVendorsInfoQueryResult = NonNullable<Awaited<ReturnType<typeof epurchaseVendorsInfo>>>
export type EpurchaseVendorsInfoQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502


export function useEpurchaseVendorsInfo<TData = Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502>(
 showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchaseVendorsInfo>>,
          TError,
          Awaited<ReturnType<typeof epurchaseVendorsInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsInfo<TData = Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502>(
 showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchaseVendorsInfo>>,
          TError,
          Awaited<ReturnType<typeof epurchaseVendorsInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchaseVendorsInfo<TData = Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502>(
 showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of upstream /api/po/getVendorInfo (full vendor profile)
 */

export function useEpurchaseVendorsInfo<TData = Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchaseVendorsInfo502>(
 showEPurchaseVendorInfoRequest: ShowEPurchaseVendorInfoRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchaseVendorsInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchaseVendorsInfoQueryOptions(showEPurchaseVendorInfoRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






