/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalsRequestsShow200Data } from './approvalsRequestsShow200Data';

export type ApprovalsRequestsShow200 = {
  data: ApprovalsRequestsShow200Data;
};
