/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalsPreviewParams = {
/**
 * @maxLength 64
 */
subject_type: string;
/**
 * @maxLength 26
 * @nullable
 */
subject_id?: string | null;
/**
 * @minimum 0
 * @nullable
 */
amount?: number | null;
};
