/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalsFlowsIndex200DataItem } from './approvalsFlowsIndex200DataItem';

export type ApprovalsFlowsIndex200 = {
  data: ApprovalsFlowsIndex200DataItem[];
  /** @nullable */
  meta: null;
};
