/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalRequestResource } from './approvalRequestResource';

export type ApprovalsRequestsActions200Data = ApprovalRequestResource & { [key: string]: unknown } & Required<Pick<ApprovalRequestResource & { [key: string]: unknown }, 'actions'>>;
