/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalsInboxStatus } from './approvalsInboxStatus';

export type ApprovalsInboxParams = {
/**
 * @nullable
 */
status?: ApprovalsInboxStatus;
/**
 * @maxLength 64
 */
subject_type?: string;
/**
 * @maxLength 26
 */
subject_id?: string;
/**
 * @maxLength 255
 */
search?: string;
/**
 * @nullable
 */
date_from?: string | null;
/**
 * @nullable
 */
date_to?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
/**
 * @minimum 1
 */
page?: number;
};
