/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

/**
 * @nullable
 */
export type ApprovalRequestResourceCurrentStep = {
  position: string;
  key: string;
  label: string;
  /** @nullable */
  assigneeId: string | null;
  /** @nullable */
  assigneeName: string | null;
} | null;
