/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalActionResourceActor = {
  id: unknown;
  /** @nullable */
  name: string | null;
};
