/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface ApprovalStepResource {
  id: unknown;
  position: number;
  key: string;
  label: string;
  actionMode: string;
  /** @nullable */
  allowedActions: unknown[] | null;
}
