/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TocaEntryResource } from './tocaEntryResource';

export type ApprovalsTocaEntriesIndex200 = {
  data: TocaEntryResource[];
  /** @nullable */
  meta: null;
};
