/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalsRequestsIndex200Meta = {
  page: number;
  perPage: number;
  total: number;
};
