/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalsPreview200DataFlow = {
  id: unknown;
  code: string;
  name: string;
  minAmount: string;
  /** @nullable */
  maxAmount: string | null;
};
