/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalsDraftsStore200Data = {
  subjectType: string;
  subjectId: string;
  assignees: string;
};
