/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalActionResourceActor } from './approvalActionResourceActor';

export interface ApprovalActionResource {
  id: unknown;
  stepPosition: number;
  stepKey: string;
  action: string;
  /** @nullable */
  comment: string | null;
  actor: ApprovalActionResourceActor;
  actedAt: string;
}
