/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalsRequestsStore201Data } from './approvalsRequestsStore201Data';

export type ApprovalsRequestsStore201 = {
  data: ApprovalsRequestsStore201Data;
  /** @nullable */
  meta: null;
};
