/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TocaEntryResource } from './tocaEntryResource';

export type ApprovalsTocaEntriesUpdate200 = {
  data: TocaEntryResource;
  /** @nullable */
  meta: null;
};
