/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalsPreview200Data } from './approvalsPreview200Data';

export type ApprovalsPreview200 = {
  data: ApprovalsPreview200Data;
  /** @nullable */
  meta: null;
};
