/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ApprovalsInboxCountStatus = typeof ApprovalsInboxCountStatus[keyof typeof ApprovalsInboxCountStatus] | null;


export const ApprovalsInboxCountStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
  returned: 'returned',
} as const;
