/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ApprovalFlowResource } from './approvalFlowResource';

export type ApprovalsFlowsIndex200DataItem = ApprovalFlowResource & { [key: string]: unknown } & Required<Pick<ApprovalFlowResource & { [key: string]: unknown }, 'setting' | 'steps'>>;
