/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UserResource } from './userResource';

export type AuthCompanyLogin200Data = {
  user: UserResource;
  access_token: string;
  expires_in: string;
  refresh_token: string;
  token_type: 'Bearer';
};
