/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { AuthRefresh200Data } from './authRefresh200Data';

export type AuthRefresh200 = {
  data: AuthRefresh200Data;
  /** @nullable */
  meta: null;
};
