/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface EntityResource {
  id: string;
  code: string;
  name: string;
  timezone: string;
  locale: string;
  /** @nullable */
  logo: string | null;
  isActive: boolean;
  /** @nullable */
  createdAt: string | null;
}
