/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EntitiesEntitiesDestroy200Data } from './entitiesEntitiesDestroy200Data';

export type EntitiesEntitiesDestroy200 = {
  data: EntitiesEntitiesDestroy200Data;
  /** @nullable */
  meta: null;
};
