/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EpurchasePosIndex200Meta } from './epurchasePosIndex200Meta';

export type EpurchasePosIndex200 = {
  data: unknown[];
  meta: EpurchasePosIndex200Meta;
};
