/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EpurchasePrsIndex200Meta } from './epurchasePrsIndex200Meta';

export type EpurchasePrsIndex200 = {
  data: unknown[];
  meta: EpurchasePrsIndex200Meta;
};
