/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type EpurchaseVendorsSearch502 = {
  statusCode: 502;
  message: 'Company list is temporarily unavailable.';
  error: 'EPurchaseUnavailable';
  /** @nullable */
  correlationId: string | null;
};
