/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type EpurchaseSuppliersIndexIsOnboard = typeof EpurchaseSuppliersIndexIsOnboard[keyof typeof EpurchaseSuppliersIndexIsOnboard];


export const EpurchaseSuppliersIndexIsOnboard = {
  NUMBER_1: '1',
} as const;
