/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EvaluationItemResource } from './evaluationItemResource';
import type { EvaluationQuotationResource } from './evaluationQuotationResource';
import type { EvaluationResourceSuppliersItem } from './evaluationResourceSuppliersItem';

export interface EvaluationResource {
  id: string;
  code: string;
  /** @nullable */
  status: string | null;
  currency: string;
  exchangeRate: number;
  /** @nullable */
  recommendationBasis: string | null;
  awardedTotal: number;
  /** @nullable */
  updatedAt: string | null;
  /** @nullable */
  createdBy?: string | null;
  suppliers: EvaluationResourceSuppliersItem[];
  items?: EvaluationItemResource[];
  quotations?: EvaluationQuotationResource[];
}
