/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EvaluationQuotationItemResource } from './evaluationQuotationItemResource';

export interface EvaluationQuotationResource {
  id: string;
  supplierCode: string;
  supplierName: string;
  /** @nullable */
  supplierPhone: string | null;
  /** @nullable */
  supplierAddress: string | null;
  discount: number;
  vat: number;
  subtotal: number;
  grandTotal: number;
  /** @nullable */
  price: string | null;
  /** @nullable */
  quality: string | null;
  /** @nullable */
  leadTime: string | null;
  /** @nullable */
  warranty: string | null;
  /** @nullable */
  paymentTerms: string | null;
  /** @nullable */
  otherRemarks: string | null;
  position: number;
  lines?: EvaluationQuotationItemResource[];
}
