/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { NotificationResource } from './notificationResource';

export type NotificationsRead200 = {
  data: NotificationResource;
  /** @nullable */
  meta: null;
};
