/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { NotificationsReadAll200Data } from './notificationsReadAll200Data';

export type NotificationsReadAll200 = {
  data: NotificationsReadAll200Data;
  /** @nullable */
  meta: null;
};
