/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { NotificationsUnreadCount200Data } from './notificationsUnreadCount200Data';

export type NotificationsUnreadCount200 = {
  data: NotificationsUnreadCount200Data;
  /** @nullable */
  meta: null;
};
