/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface ProductCategoryResource {
  id: string;
  /** @nullable */
  parentId: string | null;
  code: string;
  name: string;
  /** @nullable */
  nameKm: string | null;
  sortOrder: number;
  isActive: boolean;
  children?: ProductCategoryResource[];
}
