/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface ProductVariantResource {
  id: string;
  productId: string;
  /** @nullable */
  code: string | null;
  name: string;
  /** @nullable */
  description: string | null;
  optionValues: unknown[];
  /** @nullable */
  subUnitId: string | null;
  /** @nullable */
  purchasePrice: number | null;
  /** @nullable */
  subUnitPurchasePrice: number | null;
  /** @nullable */
  imageUrl: string | null;
  isActive: boolean;
}
