/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsItemsIndex200Meta } from './productsItemsIndex200Meta';

export type ProductsItemsIndex200 = {
  data: unknown[];
  meta: ProductsItemsIndex200Meta;
};
