/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsRefs200Data } from './productsRefs200Data';

export type ProductsRefs200 = {
  data: ProductsRefs200Data;
  /** @nullable */
  meta: null;
};
