/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsImportStoreBodyRowsItem } from './productsImportStoreBodyRowsItem';

export type ProductsImportStoreBody = {
  /**
     * @minItems 1
     * @maxItems 5000
     */
  rows: ProductsImportStoreBodyRowsItem[];
};
