/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsVariationTemplatesShow200Data } from './productsVariationTemplatesShow200Data';

export type ProductsVariationTemplatesShow200 = {
  data: ProductsVariationTemplatesShow200Data;
};
