/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductResource } from './productResource';

export type ProductsItemsShow200Data = ProductResource & { [key: string]: unknown } & Required<Pick<ProductResource & { [key: string]: unknown }, 'categoryName' | 'groupName' | 'brandName' | 'uomShortName'>>;
