/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ProductsItemsIndexType = typeof ProductsItemsIndexType[keyof typeof ProductsItemsIndexType] | null;


export const ProductsItemsIndexType = {
  single: 'single',
  variable: 'variable',
} as const;
