/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsCategoriesDestroy200Data } from './productsCategoriesDestroy200Data';

export type ProductsCategoriesDestroy200 = {
  data: ProductsCategoriesDestroy200Data;
  /** @nullable */
  meta: null;
};
