/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { VariationTemplateResource } from './variationTemplateResource';

export type ProductsVariationTemplatesIndex200 = {
  data: VariationTemplateResource[];
};
