/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsItemsShow200Data } from './productsItemsShow200Data';

export type ProductsItemsShow200 = {
  data: ProductsItemsShow200Data;
};
