/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductCategoryResource } from './productCategoryResource';

export type ProductsCategoriesShow200 = {
  data: ProductCategoryResource;
};
