/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ProductsImportStore422 = {
  statusCode: 422;
  message: string;
  error: 'ValidationException';
  /** @nullable */
  correlationId: string | null;
};
