/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsItemsUpdate200Data } from './productsItemsUpdate200Data';

export type ProductsItemsUpdate200 = {
  data: ProductsItemsUpdate200Data;
};
