/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductResource } from './productResource';

export type ProductsMergeVariation200 = {
  data: ProductResource;
  /** @nullable */
  meta: null;
};
