/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface ProductGroup {
  id: string;
  entity_id: string;
  name: string;
  /** @nullable */
  description: string | null;
  is_active: boolean;
  /** @nullable */
  created_by: number | null;
  /** @nullable */
  updated_by: number | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  deleted_at: string | null;
}
