/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ProductsItemsIndexStatus = typeof ProductsItemsIndexStatus[keyof typeof ProductsItemsIndexStatus] | null;


export const ProductsItemsIndexStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
