/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type ProductsVariationTemplatesDestroy409 = {
  /** Error overview. */
  message: string;
};
