/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsUomsStore201Data } from './productsUomsStore201Data';

export type ProductsUomsStore201 = {
  data: ProductsUomsStore201Data;
  /** @nullable */
  meta: null;
};
