/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { VariationTemplateResource } from './variationTemplateResource';

export type ProductsVariationTemplatesUpdate200Data = VariationTemplateResource & { [key: string]: unknown } & Required<Pick<VariationTemplateResource & { [key: string]: unknown }, 'options'>>;
