/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsItemsStore201Data } from './productsItemsStore201Data';

export type ProductsItemsStore201 = {
  data: ProductsItemsStore201Data;
  /** @nullable */
  meta: null;
};
