/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { ProductVariantResource } from './productVariantResource';

export interface ProductResource {
  id: string;
  code: string;
  name: string;
  /** @nullable */
  nameKm: string | null;
  /** @nullable */
  description: string | null;
  productType: string;
  /** @nullable */
  categoryId: string | null;
  /** @nullable */
  categoryName?: string | null;
  /** @nullable */
  groupId: string | null;
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  brandId: string | null;
  /** @nullable */
  brandName?: string | null;
  /** @nullable */
  uomId: string | null;
  /** @nullable */
  uomShortName?: string | null;
  /** @nullable */
  subUnitId: string | null;
  /** @nullable */
  purchasePrice: number | null;
  /** @nullable */
  subUnitPurchasePrice: number | null;
  /** @nullable */
  imageUrl: string | null;
  isActive: boolean;
  variantCount?: number;
  variants?: ProductVariantResource[];
  templateIds?: unknown[];
}
