/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface ProductGroupResource {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  isActive: boolean;
}
