/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { EvaluationResource } from './evaluationResource';

export type PurchaseOrdersEvaluationsStore201Data = EvaluationResource & { [key: string]: unknown } & Required<Pick<EvaluationResource & { [key: string]: unknown }, 'createdBy'>>;
