/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { PurchaseOrdersEvaluationsStore201Data } from './purchaseOrdersEvaluationsStore201Data';

export type PurchaseOrdersEvaluationsStore201 = {
  data: PurchaseOrdersEvaluationsStore201Data;
  /** @nullable */
  meta: null;
};
