/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { PurchaseOrdersEvaluationsIndex200Meta } from './purchaseOrdersEvaluationsIndex200Meta';

export type PurchaseOrdersEvaluationsIndex200 = {
  data: unknown[];
  meta: PurchaseOrdersEvaluationsIndex200Meta;
};
