/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { RolesRolesStore201Data } from './rolesRolesStore201Data';

export type RolesRolesStore201 = {
  data: RolesRolesStore201Data;
  /** @nullable */
  meta: null;
};
