/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { RoleResource } from './roleResource';

export type RolesRolesShow200Data = RoleResource & { [key: string]: unknown } & Required<Pick<RoleResource & { [key: string]: unknown }, 'permissions'>>;
