/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface RoleResource {
  id: number;
  name: string;
  guardName: string;
  permissions?: unknown[];
  /** @nullable */
  createdAt: string | null;
}
