/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreUomRequestSubUnitsItem } from './storeUomRequestSubUnitsItem';

export interface StoreUomRequest {
  /** @maxLength 255 */
  name: string;
  /**
     * @maxLength 16
     * @nullable
     */
  short_name?: string | null;
  is_active?: boolean;
  sub_units?: StoreUomRequestSubUnitsItem[];
}
