/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface StoreApprovalDraftRequest {
  /** @maxLength 64 */
  subject_type: string;
  /** @maxLength 26 */
  subject_id: string;
  /**
     * @minItems 1
     * @items.minimum 1
     */
  assignees: number[];
}
