/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreUserRequestRolesItem } from './storeUserRequestRolesItem';

export interface StoreUserRequest {
  /** @maxLength 255 */
  name: string;
  /** @maxLength 255 */
  email: string;
  /** @minLength 10 */
  password: string;
  is_active?: boolean;
  /** @nullable */
  entity_id?: string | null;
  roles?: StoreUserRequestRolesItem[];
}
