/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface StoreRoleRequest {
  /** @maxLength 255 */
  name: string;
  permissions?: string[];
}
