/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreEvaluationRequestQuotationsItemLinesItem } from './storeEvaluationRequestQuotationsItemLinesItem';

export type StoreEvaluationRequestQuotationsItem = {
  /** @maxLength 64 */
  supplier_code: string;
  /** @maxLength 255 */
  supplier_name: string;
  /** @maxLength 255 */
  supplier_phone: string;
  /** @maxLength 255 */
  supplier_address: string;
  /**
     * @minimum 0
     * @nullable
     */
  discount?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  vat?: number | null;
  /**
     * @maxLength 255
     * @nullable
     */
  price?: string | null;
  /**
     * @maxLength 255
     * @nullable
     */
  quality?: string | null;
  /** @nullable */
  lead_time?: string | null;
  /** @nullable */
  warranty?: string | null;
  /** @nullable */
  payment_terms?: string | null;
  /** @nullable */
  other_remarks?: string | null;
  /** @minItems 1 */
  lines: StoreEvaluationRequestQuotationsItemLinesItem[];
};
