/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreTelegramContactRequestLanguage } from './storeTelegramContactRequestLanguage';

export interface StoreTelegramContactRequest {
  /** @maxLength 100 */
  name: string;
  /**
     * @maxLength 32
     * @pattern ^\+?[0-9]{6,15}$
     */
  phone: string;
  language?: StoreTelegramContactRequestLanguage;
  /**
     * @maxLength 64
     * @nullable
     */
  supplier_code?: string | null;
  /** @nullable */
  telegram_account_id?: string | null;
}
