/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreTocaEntryRequestSubjectType } from './storeTocaEntryRequestSubjectType';

export interface StoreTocaEntryRequest {
  user_id: number;
  /** @maxLength 64 */
  subject_type: StoreTocaEntryRequestSubjectType;
  /** @minimum 0 */
  min_amount: number;
  /**
     * @minimum 0
     * @nullable
     */
  max_amount?: number | null;
}
