/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type StoreApprovalFlowRequestStepsItemAllowedActionsItem = typeof StoreApprovalFlowRequestStepsItemAllowedActionsItem[keyof typeof StoreApprovalFlowRequestStepsItemAllowedActionsItem];


export const StoreApprovalFlowRequestStepsItemAllowedActionsItem = {
  approve: 'approve',
  reject: 'reject',
  return: 'return',
} as const;
