/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreApprovalActionRequestAction } from './storeApprovalActionRequestAction';

export interface StoreApprovalActionRequest {
  action: StoreApprovalActionRequestAction;
  /**
     * @maxLength 2000
     * @nullable
     */
  comment?: string | null;
}
