/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreTelegramContactRequestLanguage } from './storeTelegramContactRequestLanguage';

export interface StoreTelegramContactRequest {
  /** @maxLength 100 */
  name: string;
  /**
     * At least one of phone / username is required to identify the
     * Telegram account; username-only contacts skip the phone upload.
     * @maxLength 32
     * @nullable
     * @pattern ^\+?[0-9]{6,15}$
     */
  phone?: string | null;
  /**
     * @maxLength 32
     * @nullable
     * @pattern ^@[A-Za-z0-9_]{5,32}$
     */
  username?: string | null;
  language?: StoreTelegramContactRequestLanguage;
  /**
     * @maxLength 64
     * @nullable
     */
  supplier_code?: string | null;
  /** @nullable */
  telegram_account_id?: string | null;
}
