/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreEvaluationRequestItemsItem } from './storeEvaluationRequestItemsItem';
import type { StoreEvaluationRequestQuotationsItem } from './storeEvaluationRequestQuotationsItem';

export interface StoreEvaluationRequest {
  /** @nullable */
  recommendation_basis?: string | null;
  /** @minItems 1 */
  items: StoreEvaluationRequestItemsItem[];
  /** @minItems 2 */
  quotations: StoreEvaluationRequestQuotationsItem[];
}
