/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type StoreApprovalFlowRequestStepsItemActionMode = typeof StoreApprovalFlowRequestStepsItemActionMode[keyof typeof StoreApprovalFlowRequestStepsItemActionMode];


export const StoreApprovalFlowRequestStepsItemActionMode = {
  record: 'record',
  decide: 'decide',
} as const;
