/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type StoreUserRequestRolesItem = typeof StoreUserRequestRolesItem[keyof typeof StoreUserRequestRolesItem];


export const StoreUserRequestRolesItem = {
  admin: 'admin',
  staff: 'staff',
} as const;
