/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { StoreEntityRequestTimezone } from './storeEntityRequestTimezone';

export interface StoreEntityRequest {
  /** @maxLength 32 */
  code: string;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 64 */
  timezone: StoreEntityRequestTimezone;
  /** @maxLength 12 */
  locale: string;
  is_active?: boolean;
}
