/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface StoreTelegramMessageRequest {
  telegram_contact_id: string;
  /** @maxLength 4000 */
  body: string;
  /** @maxLength 128 */
  idempotency_key?: string;
}
