/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type StoreEvaluationRequestQuotationsItemLinesItem = {
  /** @minimum 0 */
  item_index: number;
  /**
     * @maxLength 255
     * @nullable
     */
  brand?: string | null;
  /** @minimum 0 */
  unit_cost: number;
  is_selected?: boolean;
};
