/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TelegramContactsDestroy200Data } from './telegramContactsDestroy200Data';

export type TelegramContactsDestroy200 = {
  data: TelegramContactsDestroy200Data;
  /** @nullable */
  meta: null;
};
