/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TelegramAccountResource } from './telegramAccountResource';

export type TelegramAccountsUpdate200 = {
  data: TelegramAccountResource;
  /** @nullable */
  meta: null;
};
