/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TelegramContactResource } from './telegramContactResource';

export type TelegramContactsStore201 = {
  data: TelegramContactResource;
  /** @nullable */
  meta: null;
};
