/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TelegramAccountsHealth200Data } from './telegramAccountsHealth200Data';

export type TelegramAccountsHealth200 = {
  data: TelegramAccountsHealth200Data;
  /** @nullable */
  meta: null;
};
