/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { TelegramInternalInbound200Data } from './telegramInternalInbound200Data';

export type TelegramInternalInbound200 = {
  data: TelegramInternalInbound200Data;
  /** @nullable */
  meta: null;
};
