/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface TocaEntryResource {
  id: unknown;
  name: string;
  subjectType: string;
  /** @nullable */
  stepKey: string | null;
  minAmount: string;
  /** @nullable */
  maxAmount: string | null;
  users: string[];
}
