/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface UomSubUnitResource {
  id: string;
  uomId: string;
  name: string;
  shortName: string;
  conversionFactor: number;
  isActive: boolean;
}
