/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateEvaluationRequestItemsItem } from './updateEvaluationRequestItemsItem';
import type { UpdateEvaluationRequestQuotationsItem } from './updateEvaluationRequestQuotationsItem';

export interface UpdateEvaluationRequest {
  /** @nullable */
  recommendation_basis?: string | null;
  /** @minItems 1 */
  items: UpdateEvaluationRequestItemsItem[];
  /** @minItems 2 */
  quotations: UpdateEvaluationRequestQuotationsItem[];
}
