/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateUserRequest {
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 255 */
  email?: string;
  /** @minLength 10 */
  password?: string;
  is_active?: boolean;
  roles?: string[];
}
