/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type UpdateApprovalFlowRequestStepsItemActionMode = typeof UpdateApprovalFlowRequestStepsItemActionMode[keyof typeof UpdateApprovalFlowRequestStepsItemActionMode];


export const UpdateApprovalFlowRequestStepsItemActionMode = {
  record: 'record',
  decide: 'decide',
} as const;
