/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type UpdateEvaluationRequestCurrency = typeof UpdateEvaluationRequestCurrency[keyof typeof UpdateEvaluationRequestCurrency];


export const UpdateEvaluationRequestCurrency = {
  USD: 'USD',
  KHR: 'KHR',
} as const;
