/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateProductRequestProductType } from './updateProductRequestProductType';
import type { UpdateProductRequestVariantsItem } from './updateProductRequestVariantsItem';

export interface UpdateProductRequest {
  /** @maxLength 64 */
  code?: string;
  /** @maxLength 255 */
  name?: string;
  /**
     * @maxLength 255
     * @nullable
     */
  name_km?: string | null;
  /** @nullable */
  description?: string | null;
  product_type?: UpdateProductRequestProductType;
  /** @nullable */
  category_id?: string | null;
  /** @nullable */
  group_id?: string | null;
  /** @nullable */
  brand_id?: string | null;
  /** @nullable */
  uom_id?: string | null;
  /** @nullable */
  sub_unit_id?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  purchase_price?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  sub_unit_purchase_price?: number | null;
  is_active?: boolean;
  template_ids?: string[];
  variants?: UpdateProductRequestVariantsItem[];
}
