/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateLogoRequest {
  /** Maximum file size: 2048 kilobytes. */
  image: Blob;
}
