/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateProductCategoryRequest {
  /** @nullable */
  parent_id?: string | null;
  /** @maxLength 32 */
  code?: string;
  /** @maxLength 255 */
  name?: string;
  /**
     * @maxLength 255
     * @nullable
     */
  name_km?: string | null;
  /** @minimum 0 */
  sort_order?: number;
  is_active?: boolean;
}
