/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type UpdateProductRequestVariantsItem = {
  /**
     * @maxLength 26
     * @nullable
     */
  id?: string | null;
  /**
     * @maxLength 64
     * @nullable
     */
  code?: string | null;
  /**
     * @maxLength 255
     * @nullable
     */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /**
     * @minItems 1
     * @items.maxLength 26
     */
  option_values?: string[];
  /** @nullable */
  sub_unit_id?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  purchase_price?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  sub_unit_purchase_price?: number | null;
  is_active?: boolean;
};
