/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */

export type UpdateUserRequestRolesItem = typeof UpdateUserRequestRolesItem[keyof typeof UpdateUserRequestRolesItem];


export const UpdateUserRequestRolesItem = {
  admin: 'admin',
  staff: 'staff',
} as const;
