/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UsersUsersUpdate200Data } from './usersUsersUpdate200Data';

export type UsersUsersUpdate200 = {
  data: UsersUsersUpdate200Data;
};
