/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UsersUsersStore201Data } from './usersUsersStore201Data';

export type UsersUsersStore201 = {
  data: UsersUsersStore201Data;
  /** @nullable */
  meta: null;
};
