/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { UsersUsersShow200Data } from './usersUsersShow200Data';

export type UsersUsersShow200 = {
  data: UsersUsersShow200Data;
};
