/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import type { VariationTemplateResourceOptionsItem } from './variationTemplateResourceOptionsItem';

export interface VariationTemplateResource {
  id: string;
  name: string;
  isActive: boolean;
  options?: VariationTemplateResourceOptionsItem[];
}
