/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  EpurchasePosIndex200,
  EpurchasePosIndex502,
  EpurchasePosIndexParams,
  EpurchasePosShow200,
  EpurchasePosShow502,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type epurchasePosIndexResponse200 = {
  data: EpurchasePosIndex200
  status: 200
}

export type epurchasePosIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchasePosIndexResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type epurchasePosIndexResponse502 = {
  data: EpurchasePosIndex502
  status: 502
}

export type epurchasePosIndexResponseSuccess = (epurchasePosIndexResponse200) & {
  headers: Headers;
};
export type epurchasePosIndexResponseError = (epurchasePosIndexResponse401 | epurchasePosIndexResponse422 | epurchasePosIndexResponse502) & {
  headers: Headers;
};

export type epurchasePosIndexResponse = (epurchasePosIndexResponseSuccess | epurchasePosIndexResponseError)

export const getEpurchasePosIndexUrl = (params?: EpurchasePosIndexParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/pos?${stringifiedParams}` : `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/pos`
}

/**
 * @summary Read-only proxy of the upstream purchase order list (server-side paging/search)
 */
export const epurchasePosIndex = async (params?: EpurchasePosIndexParams, options?: RequestInit): Promise<epurchasePosIndexResponse> => {

  const res = await fetch(getEpurchasePosIndexUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchasePosIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchasePosIndexResponse
}





export const getEpurchasePosIndexQueryKey = (params?: EpurchasePosIndexParams,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/pos`, ...(params ? [params] : [])
    ] as const;
    }


export const getEpurchasePosIndexQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(params?: EpurchasePosIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePosIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePosIndex>>> = ({ signal }) => epurchasePosIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePosIndexQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePosIndex>>>
export type EpurchasePosIndexQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502


export function useEpurchasePosIndex<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params: undefined |  EpurchasePosIndexParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePosIndex>>,
          TError,
          Awaited<ReturnType<typeof epurchasePosIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosIndex<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePosIndex>>,
          TError,
          Awaited<ReturnType<typeof epurchasePosIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosIndex<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of the upstream purchase order list (server-side paging/search)
 */

export function useEpurchasePosIndex<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePosIndexQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEpurchasePosIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(params?: EpurchasePosIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePosIndexQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePosIndex>>> = ({ signal }) => epurchasePosIndex(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePosIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePosIndex>>>
export type EpurchasePosIndexSuspenseQueryError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502


export function useEpurchasePosIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params: undefined |  EpurchasePosIndexParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of the upstream purchase order list (server-side paging/search)
 */

export function useEpurchasePosIndexSuspense<TData = Awaited<ReturnType<typeof epurchasePosIndex>>, TError = AuthenticationExceptionResponse | ValidationExceptionResponse | EpurchasePosIndex502>(
 params?: EpurchasePosIndexParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePosIndexSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type epurchasePosShowResponse200 = {
  data: EpurchasePosShow200
  status: 200
}

export type epurchasePosShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type epurchasePosShowResponse502 = {
  data: EpurchasePosShow502
  status: 502
}

export type epurchasePosShowResponseSuccess = (epurchasePosShowResponse200) & {
  headers: Headers;
};
export type epurchasePosShowResponseError = (epurchasePosShowResponse401 | epurchasePosShowResponse502) & {
  headers: Headers;
};

export type epurchasePosShowResponse = (epurchasePosShowResponseSuccess | epurchasePosShowResponseError)

export const getEpurchasePosShowUrl = (poId: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/pos/${poId}`
}

/**
 * @summary Read-only proxy of one upstream purchase order's line items.
The route constrains {poId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */
export const epurchasePosShow = async (poId: string, options?: RequestInit): Promise<epurchasePosShowResponse> => {

  const res = await fetch(getEpurchasePosShowUrl(poId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: epurchasePosShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as epurchasePosShowResponse
}





export const getEpurchasePosShowQueryKey = (poId: string,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/epurchase/pos/${poId}`
    ] as const;
    }


export const getEpurchasePosShowQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(poId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePosShowQueryKey(poId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePosShow>>> = ({ signal }) => epurchasePosShow(poId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: poId !== null && poId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePosShowQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePosShow>>>
export type EpurchasePosShowQueryError = AuthenticationExceptionResponse | EpurchasePosShow502


export function useEpurchasePosShow<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePosShow>>,
          TError,
          Awaited<ReturnType<typeof epurchasePosShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosShow<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof epurchasePosShow>>,
          TError,
          Awaited<ReturnType<typeof epurchasePosShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosShow<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of one upstream purchase order's line items.
The route constrains {poId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */

export function useEpurchasePosShow<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePosShowQueryOptions(poId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getEpurchasePosShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(poId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEpurchasePosShowQueryKey(poId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof epurchasePosShow>>> = ({ signal }) => epurchasePosShow(poId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EpurchasePosShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof epurchasePosShow>>>
export type EpurchasePosShowSuspenseQueryError = AuthenticationExceptionResponse | EpurchasePosShow502


export function useEpurchasePosShowSuspense<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosShowSuspense<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEpurchasePosShowSuspense<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read-only proxy of one upstream purchase order's line items.
The route constrains {poId} to numbers (a non-numeric id is a 404,
mirroring how model binding rejects unknown record ids)
 */

export function useEpurchasePosShowSuspense<TData = Awaited<ReturnType<typeof epurchasePosShow>>, TError = AuthenticationExceptionResponse | EpurchasePosShow502>(
 poId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof epurchasePosShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEpurchasePosShowSuspenseQueryOptions(poId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






