/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  ApprovalsSettingsIndex200,
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type approvalsSettingsIndexResponse200 = {
  data: ApprovalsSettingsIndex200
  status: 200
}

export type approvalsSettingsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type approvalsSettingsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type approvalsSettingsIndexResponseSuccess = (approvalsSettingsIndexResponse200) & {
  headers: Headers;
};
export type approvalsSettingsIndexResponseError = (approvalsSettingsIndexResponse401 | approvalsSettingsIndexResponse403) & {
  headers: Headers;
};

export type approvalsSettingsIndexResponse = (approvalsSettingsIndexResponseSuccess | approvalsSettingsIndexResponseError)

export const getApprovalsSettingsIndexUrl = () => {




  return `http://localhost:8000/api/v1/approvals/settings`
}

/**
 * @summary Settings are seeded per subject type and read-only for now; the
configuration screens need them as their vocabulary (which document
types can be configured) and to anchor the flows beneath each one
 */
export const approvalsSettingsIndex = async ( options?: RequestInit): Promise<approvalsSettingsIndexResponse> => {

  const res = await fetch(getApprovalsSettingsIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: approvalsSettingsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as approvalsSettingsIndexResponse
}





export const getApprovalsSettingsIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/approvals/settings`
    ] as const;
    }


export const getApprovalsSettingsIndexQueryOptions = <TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsSettingsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsSettingsIndex>>> = ({ signal }) => approvalsSettingsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsSettingsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsSettingsIndex>>>
export type ApprovalsSettingsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useApprovalsSettingsIndex<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsSettingsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsSettingsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsSettingsIndex<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof approvalsSettingsIndex>>,
          TError,
          Awaited<ReturnType<typeof approvalsSettingsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsSettingsIndex<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Settings are seeded per subject type and read-only for now; the
configuration screens need them as their vocabulary (which document
types can be configured) and to anchor the flows beneath each one
 */

export function useApprovalsSettingsIndex<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsSettingsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApprovalsSettingsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApprovalsSettingsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof approvalsSettingsIndex>>> = ({ signal }) => approvalsSettingsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApprovalsSettingsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof approvalsSettingsIndex>>>
export type ApprovalsSettingsIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useApprovalsSettingsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsSettingsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApprovalsSettingsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Settings are seeded per subject type and read-only for now; the
configuration screens need them as their vocabulary (which document
types can be configured) and to anchor the flows beneath each one
 */

export function useApprovalsSettingsIndexSuspense<TData = Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof approvalsSettingsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApprovalsSettingsIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






