/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StoreUserRequest,
  UpdateUserRequest,
  UsersUsersDestroy200,
  UsersUsersIndex200,
  UsersUsersShow200,
  UsersUsersStore201,
  UsersUsersUpdate200,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type usersUsersIndexResponse200 = {
  data: UsersUsersIndex200
  status: 200
}

export type usersUsersIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersUsersIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersUsersIndexResponseSuccess = (usersUsersIndexResponse200) & {
  headers: Headers;
};
export type usersUsersIndexResponseError = (usersUsersIndexResponse401 | usersUsersIndexResponse403) & {
  headers: Headers;
};

export type usersUsersIndexResponse = (usersUsersIndexResponseSuccess | usersUsersIndexResponseError)

export const getUsersUsersIndexUrl = () => {




  return `http://localhost:8000/api/v1/users`
}

export const usersUsersIndex = async ( options?: RequestInit): Promise<usersUsersIndexResponse> => {

  const res = await fetch(getUsersUsersIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersUsersIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersUsersIndexResponse
}





export const getUsersUsersIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/users`
    ] as const;
    }


export const getUsersUsersIndexQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersIndex>>> = ({ signal }) => usersUsersIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersIndexQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersIndex>>>
export type UsersUsersIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useUsersUsersIndex<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersIndex>>,
          TError,
          Awaited<ReturnType<typeof usersUsersIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersIndex<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersIndex>>,
          TError,
          Awaited<ReturnType<typeof usersUsersIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersIndex<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersIndex<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUsersUsersIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersIndex>>> = ({ signal }) => usersUsersIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersIndex>>>
export type UsersUsersIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useUsersUsersIndexSuspense<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersIndexSuspense<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersIndexSuspense<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersIndexSuspense<TData = Awaited<ReturnType<typeof usersUsersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usersUsersStoreResponse201 = {
  data: UsersUsersStore201
  status: 201
}

export type usersUsersStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersUsersStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersUsersStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type usersUsersStoreResponseSuccess = (usersUsersStoreResponse201) & {
  headers: Headers;
};
export type usersUsersStoreResponseError = (usersUsersStoreResponse401 | usersUsersStoreResponse403 | usersUsersStoreResponse422) & {
  headers: Headers;
};

export type usersUsersStoreResponse = (usersUsersStoreResponseSuccess | usersUsersStoreResponseError)

export const getUsersUsersStoreUrl = () => {




  return `http://localhost:8000/api/v1/users`
}

export const usersUsersStore = async (storeUserRequest: StoreUserRequest, options?: RequestInit): Promise<usersUsersStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getUsersUsersStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeUserRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersUsersStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersUsersStoreResponse
}





export const getUsersUsersStoreQueryKey = (storeUserRequest?: StoreUserRequest,) => {
    return [
    'POST', `http://localhost:8000/api/v1/users`, storeUserRequest
    ] as const;
    }


export const getUsersUsersStoreQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(storeUserRequest: StoreUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersStoreQueryKey(storeUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersStore>>> = ({ signal }) => usersUsersStore(storeUserRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersStoreQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersStore>>>
export type UsersUsersStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useUsersUsersStore<TData = Awaited<ReturnType<typeof usersUsersStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeUserRequest: StoreUserRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersStore>>,
          TError,
          Awaited<ReturnType<typeof usersUsersStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersStore<TData = Awaited<ReturnType<typeof usersUsersStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeUserRequest: StoreUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersStore>>,
          TError,
          Awaited<ReturnType<typeof usersUsersStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersStore<TData = Awaited<ReturnType<typeof usersUsersStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeUserRequest: StoreUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersStore<TData = Awaited<ReturnType<typeof usersUsersStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeUserRequest: StoreUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersStoreQueryOptions(storeUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usersUsersShowResponse200 = {
  data: UsersUsersShow200
  status: 200
}

export type usersUsersShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersUsersShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersUsersShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type usersUsersShowResponseSuccess = (usersUsersShowResponse200) & {
  headers: Headers;
};
export type usersUsersShowResponseError = (usersUsersShowResponse401 | usersUsersShowResponse403 | usersUsersShowResponse404) & {
  headers: Headers;
};

export type usersUsersShowResponse = (usersUsersShowResponseSuccess | usersUsersShowResponseError)

export const getUsersUsersShowUrl = (user: number,) => {




  return `http://localhost:8000/api/v1/users/${user}`
}

export const usersUsersShow = async (user: number, options?: RequestInit): Promise<usersUsersShowResponse> => {

  const res = await fetch(getUsersUsersShowUrl(user),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersUsersShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersUsersShowResponse
}





export const getUsersUsersShowQueryKey = (user: number,) => {
    return [
    `http://localhost:8000/api/v1/users/${user}`
    ] as const;
    }


export const getUsersUsersShowQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersShowQueryKey(user);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersShow>>> = ({ signal }) => usersUsersShow(user, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: user !== null && user !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersShowQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersShow>>>
export type UsersUsersShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useUsersUsersShow<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersShow>>,
          TError,
          Awaited<ReturnType<typeof usersUsersShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersShow<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersShow>>,
          TError,
          Awaited<ReturnType<typeof usersUsersShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersShow<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersShow<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersShowQueryOptions(user,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getUsersUsersShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(user: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersShowQueryKey(user);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersShow>>> = ({ signal }) => usersUsersShow(user, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersShow>>>
export type UsersUsersShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useUsersUsersShowSuspense<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersShowSuspense<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersShowSuspense<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersShowSuspense<TData = Awaited<ReturnType<typeof usersUsersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof usersUsersShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersShowSuspenseQueryOptions(user,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usersUsersUpdateResponse200 = {
  data: UsersUsersUpdate200
  status: 200
}

export type usersUsersUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersUsersUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersUsersUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type usersUsersUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type usersUsersUpdateResponseSuccess = (usersUsersUpdateResponse200) & {
  headers: Headers;
};
export type usersUsersUpdateResponseError = (usersUsersUpdateResponse401 | usersUsersUpdateResponse403 | usersUsersUpdateResponse404 | usersUsersUpdateResponse422) & {
  headers: Headers;
};

export type usersUsersUpdateResponse = (usersUsersUpdateResponseSuccess | usersUsersUpdateResponseError)

export const getUsersUsersUpdateUrl = (user: number,) => {




  return `http://localhost:8000/api/v1/users/${user}`
}

export const usersUsersUpdate = async (user: number,
    updateUserRequest?: UpdateUserRequest, options?: RequestInit): Promise<usersUsersUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getUsersUsersUpdateUrl(user),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateUserRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersUsersUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersUsersUpdateResponse
}





export const getUsersUsersUpdateQueryKey = (user: number,
    updateUserRequest?: UpdateUserRequest,) => {
    return [
    'PUT', `http://localhost:8000/api/v1/users/${user}`, updateUserRequest
    ] as const;
    }


export const getUsersUsersUpdateQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(user: number,
    updateUserRequest?: UpdateUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersUpdateQueryKey(user,updateUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersUpdate>>> = ({ signal }) => usersUsersUpdate(user,updateUserRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: user !== null && user !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersUpdate>>>
export type UsersUsersUpdateQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useUsersUsersUpdate<TData = Awaited<ReturnType<typeof usersUsersUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 user: number,
    updateUserRequest: undefined |  UpdateUserRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersUpdate>>,
          TError,
          Awaited<ReturnType<typeof usersUsersUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersUpdate<TData = Awaited<ReturnType<typeof usersUsersUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 user: number,
    updateUserRequest?: UpdateUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersUpdate>>,
          TError,
          Awaited<ReturnType<typeof usersUsersUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersUpdate<TData = Awaited<ReturnType<typeof usersUsersUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 user: number,
    updateUserRequest?: UpdateUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersUpdate<TData = Awaited<ReturnType<typeof usersUsersUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 user: number,
    updateUserRequest?: UpdateUserRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersUpdateQueryOptions(user,updateUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usersUsersDestroyResponse200 = {
  data: UsersUsersDestroy200
  status: 200
}

export type usersUsersDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersUsersDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersUsersDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type usersUsersDestroyResponseSuccess = (usersUsersDestroyResponse200) & {
  headers: Headers;
};
export type usersUsersDestroyResponseError = (usersUsersDestroyResponse401 | usersUsersDestroyResponse403 | usersUsersDestroyResponse404) & {
  headers: Headers;
};

export type usersUsersDestroyResponse = (usersUsersDestroyResponseSuccess | usersUsersDestroyResponseError)

export const getUsersUsersDestroyUrl = (user: number,) => {




  return `http://localhost:8000/api/v1/users/${user}`
}

export const usersUsersDestroy = async (user: number, options?: RequestInit): Promise<usersUsersDestroyResponse> => {

  const res = await fetch(getUsersUsersDestroyUrl(user),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usersUsersDestroyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersUsersDestroyResponse
}





export const getUsersUsersDestroyQueryKey = (user: number,) => {
    return [
    'DELETE', `http://localhost:8000/api/v1/users/${user}`
    ] as const;
    }


export const getUsersUsersDestroyQueryOptions = <TData = Awaited<ReturnType<typeof usersUsersDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUsersDestroyQueryKey(user);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUsersDestroy>>> = ({ signal }) => usersUsersDestroy(user, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: user !== null && user !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUsersDestroyQueryResult = NonNullable<Awaited<ReturnType<typeof usersUsersDestroy>>>
export type UsersUsersDestroyQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useUsersUsersDestroy<TData = Awaited<ReturnType<typeof usersUsersDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersDestroy>>,
          TError,
          Awaited<ReturnType<typeof usersUsersDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersDestroy<TData = Awaited<ReturnType<typeof usersUsersDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUsersDestroy>>,
          TError,
          Awaited<ReturnType<typeof usersUsersDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUsersDestroy<TData = Awaited<ReturnType<typeof usersUsersDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersUsersDestroy<TData = Awaited<ReturnType<typeof usersUsersDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUsersDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUsersDestroyQueryOptions(user,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






