/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  LoginCodeRequest,
  LoginPasswordRequest,
  ModelNotFoundExceptionResponse,
  StoreTelegramAccountRequest,
  TelegramAccountsDestroy200,
  TelegramAccountsHealth200,
  TelegramAccountsIndex200,
  TelegramAccountsLoginCode200,
  TelegramAccountsLoginPassword200,
  TelegramAccountsShow200,
  TelegramAccountsStore201,
  TelegramAccountsUpdate200,
  UpdateTelegramAccountRequest,
  ValidationExceptionResponse
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type telegramAccountsLoginCodeResponse200 = {
  data: TelegramAccountsLoginCode200
  status: 200
}

export type telegramAccountsLoginCodeResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsLoginCodeResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsLoginCodeResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsLoginCodeResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramAccountsLoginCodeResponseSuccess = (telegramAccountsLoginCodeResponse200) & {
  headers: Headers;
};
export type telegramAccountsLoginCodeResponseError = (telegramAccountsLoginCodeResponse401 | telegramAccountsLoginCodeResponse403 | telegramAccountsLoginCodeResponse404 | telegramAccountsLoginCodeResponse422) & {
  headers: Headers;
};

export type telegramAccountsLoginCodeResponse = (telegramAccountsLoginCodeResponseSuccess | telegramAccountsLoginCodeResponseError)

export const getTelegramAccountsLoginCodeUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/login-code`
}

export const telegramAccountsLoginCode = async (account: string,
    loginCodeRequest: LoginCodeRequest, options?: RequestInit): Promise<telegramAccountsLoginCodeResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getTelegramAccountsLoginCodeUrl(account),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginCodeRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsLoginCodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsLoginCodeResponse
}





export const getTelegramAccountsLoginCodeQueryKey = (account: string,
    loginCodeRequest?: LoginCodeRequest,) => {
    return [
    'POST', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/login-code`, loginCodeRequest
    ] as const;
    }


export const getTelegramAccountsLoginCodeQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(account: string,
    loginCodeRequest: LoginCodeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsLoginCodeQueryKey(account,loginCodeRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsLoginCode>>> = ({ signal }) => telegramAccountsLoginCode(account,loginCodeRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsLoginCodeQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsLoginCode>>>
export type TelegramAccountsLoginCodeQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useTelegramAccountsLoginCode<TData = Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginCodeRequest: LoginCodeRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsLoginCode>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsLoginCode>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsLoginCode<TData = Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginCodeRequest: LoginCodeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsLoginCode>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsLoginCode>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsLoginCode<TData = Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginCodeRequest: LoginCodeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsLoginCode<TData = Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginCodeRequest: LoginCodeRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginCode>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsLoginCodeQueryOptions(account,loginCodeRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsLoginPasswordResponse200 = {
  data: TelegramAccountsLoginPassword200
  status: 200
}

export type telegramAccountsLoginPasswordResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsLoginPasswordResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsLoginPasswordResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsLoginPasswordResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramAccountsLoginPasswordResponseSuccess = (telegramAccountsLoginPasswordResponse200) & {
  headers: Headers;
};
export type telegramAccountsLoginPasswordResponseError = (telegramAccountsLoginPasswordResponse401 | telegramAccountsLoginPasswordResponse403 | telegramAccountsLoginPasswordResponse404 | telegramAccountsLoginPasswordResponse422) & {
  headers: Headers;
};

export type telegramAccountsLoginPasswordResponse = (telegramAccountsLoginPasswordResponseSuccess | telegramAccountsLoginPasswordResponseError)

export const getTelegramAccountsLoginPasswordUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/login-password`
}

export const telegramAccountsLoginPassword = async (account: string,
    loginPasswordRequest: LoginPasswordRequest, options?: RequestInit): Promise<telegramAccountsLoginPasswordResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getTelegramAccountsLoginPasswordUrl(account),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginPasswordRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsLoginPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsLoginPasswordResponse
}





export const getTelegramAccountsLoginPasswordQueryKey = (account: string,
    loginPasswordRequest?: LoginPasswordRequest,) => {
    return [
    'POST', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/login-password`, loginPasswordRequest
    ] as const;
    }


export const getTelegramAccountsLoginPasswordQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(account: string,
    loginPasswordRequest: LoginPasswordRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsLoginPasswordQueryKey(account,loginPasswordRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>> = ({ signal }) => telegramAccountsLoginPassword(account,loginPasswordRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsLoginPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>>
export type TelegramAccountsLoginPasswordQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useTelegramAccountsLoginPassword<TData = Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginPasswordRequest: LoginPasswordRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsLoginPassword>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsLoginPassword>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsLoginPassword<TData = Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginPasswordRequest: LoginPasswordRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsLoginPassword>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsLoginPassword>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsLoginPassword<TData = Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginPasswordRequest: LoginPasswordRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsLoginPassword<TData = Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    loginPasswordRequest: LoginPasswordRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsLoginPassword>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsLoginPasswordQueryOptions(account,loginPasswordRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsHealthResponse200 = {
  data: TelegramAccountsHealth200
  status: 200
}

export type telegramAccountsHealthResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsHealthResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsHealthResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsHealthResponseSuccess = (telegramAccountsHealthResponse200) & {
  headers: Headers;
};
export type telegramAccountsHealthResponseError = (telegramAccountsHealthResponse401 | telegramAccountsHealthResponse403 | telegramAccountsHealthResponse404) & {
  headers: Headers;
};

export type telegramAccountsHealthResponse = (telegramAccountsHealthResponseSuccess | telegramAccountsHealthResponseError)

export const getTelegramAccountsHealthUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/health`
}

export const telegramAccountsHealth = async (account: string, options?: RequestInit): Promise<telegramAccountsHealthResponse> => {

  const res = await fetch(getTelegramAccountsHealthUrl(account),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsHealthResponse
}





export const getTelegramAccountsHealthQueryKey = (account: string,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}/health`
    ] as const;
    }


export const getTelegramAccountsHealthQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsHealthQueryKey(account);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsHealth>>> = ({ signal }) => telegramAccountsHealth(account, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsHealthQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsHealth>>>
export type TelegramAccountsHealthQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTelegramAccountsHealth<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsHealth>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsHealth<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsHealth>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsHealth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsHealth<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsHealth<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsHealthQueryOptions(account,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTelegramAccountsHealthSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsHealthQueryKey(account);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsHealth>>> = ({ signal }) => telegramAccountsHealth(account, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsHealthSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsHealth>>>
export type TelegramAccountsHealthSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTelegramAccountsHealthSuspense<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsHealthSuspense<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsHealthSuspense<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsHealthSuspense<TData = Awaited<ReturnType<typeof telegramAccountsHealth>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsHealth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsHealthSuspenseQueryOptions(account,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsIndexResponse200 = {
  data: TelegramAccountsIndex200
  status: 200
}

export type telegramAccountsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsIndexResponseSuccess = (telegramAccountsIndexResponse200) & {
  headers: Headers;
};
export type telegramAccountsIndexResponseError = (telegramAccountsIndexResponse401 | telegramAccountsIndexResponse403) & {
  headers: Headers;
};

export type telegramAccountsIndexResponse = (telegramAccountsIndexResponseSuccess | telegramAccountsIndexResponseError)

export const getTelegramAccountsIndexUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts`
}

export const telegramAccountsIndex = async ( options?: RequestInit): Promise<telegramAccountsIndexResponse> => {

  const res = await fetch(getTelegramAccountsIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsIndexResponse
}





export const getTelegramAccountsIndexQueryKey = () => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts`
    ] as const;
    }


export const getTelegramAccountsIndexQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsIndex>>> = ({ signal }) => telegramAccountsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsIndex>>>
export type TelegramAccountsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useTelegramAccountsIndex<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsIndex>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsIndex<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsIndex>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsIndex<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsIndex<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTelegramAccountsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsIndex>>> = ({ signal }) => telegramAccountsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsIndex>>>
export type TelegramAccountsIndexSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useTelegramAccountsIndexSuspense<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsIndexSuspense<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsIndexSuspense<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsIndexSuspense<TData = Awaited<ReturnType<typeof telegramAccountsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsStoreResponse201 = {
  data: TelegramAccountsStore201
  status: 201
}

export type telegramAccountsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramAccountsStoreResponseSuccess = (telegramAccountsStoreResponse201) & {
  headers: Headers;
};
export type telegramAccountsStoreResponseError = (telegramAccountsStoreResponse401 | telegramAccountsStoreResponse403 | telegramAccountsStoreResponse422) & {
  headers: Headers;
};

export type telegramAccountsStoreResponse = (telegramAccountsStoreResponseSuccess | telegramAccountsStoreResponseError)

export const getTelegramAccountsStoreUrl = () => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts`
}

export const telegramAccountsStore = async (storeTelegramAccountRequest: StoreTelegramAccountRequest, options?: RequestInit): Promise<telegramAccountsStoreResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getTelegramAccountsStoreUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(storeTelegramAccountRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsStoreResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsStoreResponse
}





export const getTelegramAccountsStoreQueryKey = (storeTelegramAccountRequest?: StoreTelegramAccountRequest,) => {
    return [
    'POST', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts`, storeTelegramAccountRequest
    ] as const;
    }


export const getTelegramAccountsStoreQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(storeTelegramAccountRequest: StoreTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsStoreQueryKey(storeTelegramAccountRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsStore>>> = ({ signal }) => telegramAccountsStore(storeTelegramAccountRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsStoreQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsStore>>>
export type TelegramAccountsStoreQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse


export function useTelegramAccountsStore<TData = Awaited<ReturnType<typeof telegramAccountsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeTelegramAccountRequest: StoreTelegramAccountRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsStore>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsStore<TData = Awaited<ReturnType<typeof telegramAccountsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeTelegramAccountRequest: StoreTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsStore>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsStore>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsStore<TData = Awaited<ReturnType<typeof telegramAccountsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeTelegramAccountRequest: StoreTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsStore<TData = Awaited<ReturnType<typeof telegramAccountsStore>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse>(
 storeTelegramAccountRequest: StoreTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsStore>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsStoreQueryOptions(storeTelegramAccountRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsShowResponse200 = {
  data: TelegramAccountsShow200
  status: 200
}

export type telegramAccountsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsShowResponseSuccess = (telegramAccountsShowResponse200) & {
  headers: Headers;
};
export type telegramAccountsShowResponseError = (telegramAccountsShowResponse401 | telegramAccountsShowResponse403 | telegramAccountsShowResponse404) & {
  headers: Headers;
};

export type telegramAccountsShowResponse = (telegramAccountsShowResponseSuccess | telegramAccountsShowResponseError)

export const getTelegramAccountsShowUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`
}

export const telegramAccountsShow = async (account: string, options?: RequestInit): Promise<telegramAccountsShowResponse> => {

  const res = await fetch(getTelegramAccountsShowUrl(account),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsShowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsShowResponse
}





export const getTelegramAccountsShowQueryKey = (account: string,) => {
    return [
    `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`
    ] as const;
    }


export const getTelegramAccountsShowQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsShowQueryKey(account);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsShow>>> = ({ signal }) => telegramAccountsShow(account, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsShowQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsShow>>>
export type TelegramAccountsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTelegramAccountsShow<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsShow>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsShow<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsShow>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsShow>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsShow<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsShow<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsShowQueryOptions(account,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTelegramAccountsShowSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsShowQueryKey(account);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsShow>>> = ({ signal }) => telegramAccountsShow(account, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsShowSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsShow>>>
export type TelegramAccountsShowSuspenseQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTelegramAccountsShowSuspense<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsShowSuspense<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsShowSuspense<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsShowSuspense<TData = Awaited<ReturnType<typeof telegramAccountsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof telegramAccountsShow>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsShowSuspenseQueryOptions(account,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsUpdateResponse200 = {
  data: TelegramAccountsUpdate200
  status: 200
}

export type telegramAccountsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type telegramAccountsUpdateResponseSuccess = (telegramAccountsUpdateResponse200) & {
  headers: Headers;
};
export type telegramAccountsUpdateResponseError = (telegramAccountsUpdateResponse401 | telegramAccountsUpdateResponse403 | telegramAccountsUpdateResponse404 | telegramAccountsUpdateResponse422) & {
  headers: Headers;
};

export type telegramAccountsUpdateResponse = (telegramAccountsUpdateResponseSuccess | telegramAccountsUpdateResponseError)

export const getTelegramAccountsUpdateUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`
}

export const telegramAccountsUpdate = async (account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest, options?: RequestInit): Promise<telegramAccountsUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getTelegramAccountsUpdateUrl(account),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTelegramAccountRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsUpdateResponse
}





export const getTelegramAccountsUpdateQueryKey = (account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest,) => {
    return [
    'PUT', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`, updateTelegramAccountRequest
    ] as const;
    }


export const getTelegramAccountsUpdateQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsUpdateQueryKey(account,updateTelegramAccountRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsUpdate>>> = ({ signal }) => telegramAccountsUpdate(account,updateTelegramAccountRequest, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsUpdateQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsUpdate>>>
export type TelegramAccountsUpdateQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse


export function useTelegramAccountsUpdate<TData = Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    updateTelegramAccountRequest: undefined |  UpdateTelegramAccountRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsUpdate>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsUpdate<TData = Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsUpdate>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsUpdate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsUpdate<TData = Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsUpdate<TData = Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse>(
 account: string,
    updateTelegramAccountRequest?: UpdateTelegramAccountRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsUpdate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsUpdateQueryOptions(account,updateTelegramAccountRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type telegramAccountsDestroyResponse200 = {
  data: TelegramAccountsDestroy200
  status: 200
}

export type telegramAccountsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type telegramAccountsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type telegramAccountsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type telegramAccountsDestroyResponseSuccess = (telegramAccountsDestroyResponse200) & {
  headers: Headers;
};
export type telegramAccountsDestroyResponseError = (telegramAccountsDestroyResponse401 | telegramAccountsDestroyResponse403 | telegramAccountsDestroyResponse404) & {
  headers: Headers;
};

export type telegramAccountsDestroyResponse = (telegramAccountsDestroyResponseSuccess | telegramAccountsDestroyResponseError)

export const getTelegramAccountsDestroyUrl = (account: string,) => {




  return `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`
}

export const telegramAccountsDestroy = async (account: string, options?: RequestInit): Promise<telegramAccountsDestroyResponse> => {

  const res = await fetch(getTelegramAccountsDestroyUrl(account),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: telegramAccountsDestroyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as telegramAccountsDestroyResponse
}





export const getTelegramAccountsDestroyQueryKey = (account: string,) => {
    return [
    'DELETE', `${process.env.NEXT_PUBLIC_API_URL}/api/v1/telegram/accounts/${account}`
    ] as const;
    }


export const getTelegramAccountsDestroyQueryOptions = <TData = Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTelegramAccountsDestroyQueryKey(account);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof telegramAccountsDestroy>>> = ({ signal }) => telegramAccountsDestroy(account, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: account !== null && account !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TelegramAccountsDestroyQueryResult = NonNullable<Awaited<ReturnType<typeof telegramAccountsDestroy>>>
export type TelegramAccountsDestroyQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTelegramAccountsDestroy<TData = Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsDestroy>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsDestroy<TData = Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof telegramAccountsDestroy>>,
          TError,
          Awaited<ReturnType<typeof telegramAccountsDestroy>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTelegramAccountsDestroy<TData = Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTelegramAccountsDestroy<TData = Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 account: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof telegramAccountsDestroy>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTelegramAccountsDestroyQueryOptions(account,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






