/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Procurement
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  ModelNotFoundExceptionResponse,
  NotificationsIndex200,
  NotificationsRead200,
  NotificationsReadAll200,
  NotificationsUnreadCount200
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type notificationsUnreadCountResponse200 = {
  data: NotificationsUnreadCount200
  status: 200
}

export type notificationsUnreadCountResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type notificationsUnreadCountResponseSuccess = (notificationsUnreadCountResponse200) & {
  headers: Headers;
};
export type notificationsUnreadCountResponseError = (notificationsUnreadCountResponse401) & {
  headers: Headers;
};

export type notificationsUnreadCountResponse = (notificationsUnreadCountResponseSuccess | notificationsUnreadCountResponseError)

export const getNotificationsUnreadCountUrl = () => {




  return `http://localhost:8000/api/v1/notifications/unread-count`
}

export const notificationsUnreadCount = async ( options?: RequestInit): Promise<notificationsUnreadCountResponse> => {

  const res = await fetch(getNotificationsUnreadCountUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notificationsUnreadCountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsUnreadCountResponse
}





export const getNotificationsUnreadCountQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/notifications/unread-count`
    ] as const;
    }


export const getNotificationsUnreadCountQueryOptions = <TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsUnreadCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsUnreadCount>>> = ({ signal }) => notificationsUnreadCount({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsUnreadCountQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsUnreadCount>>>
export type NotificationsUnreadCountQueryError = AuthenticationExceptionResponse


export function useNotificationsUnreadCount<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof notificationsUnreadCount>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsUnreadCount<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof notificationsUnreadCount>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsUnreadCount<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsUnreadCount<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsUnreadCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getNotificationsUnreadCountSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsUnreadCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsUnreadCount>>> = ({ signal }) => notificationsUnreadCount({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsUnreadCountSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsUnreadCount>>>
export type NotificationsUnreadCountSuspenseQueryError = AuthenticationExceptionResponse


export function useNotificationsUnreadCountSuspense<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsUnreadCountSuspense<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsUnreadCountSuspense<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsUnreadCountSuspense<TData = Awaited<ReturnType<typeof notificationsUnreadCount>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsUnreadCount>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsUnreadCountSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationsReadAllResponse200 = {
  data: NotificationsReadAll200
  status: 200
}

export type notificationsReadAllResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type notificationsReadAllResponseSuccess = (notificationsReadAllResponse200) & {
  headers: Headers;
};
export type notificationsReadAllResponseError = (notificationsReadAllResponse401) & {
  headers: Headers;
};

export type notificationsReadAllResponse = (notificationsReadAllResponseSuccess | notificationsReadAllResponseError)

export const getNotificationsReadAllUrl = () => {




  return `http://localhost:8000/api/v1/notifications/read-all`
}

export const notificationsReadAll = async ( options?: RequestInit): Promise<notificationsReadAllResponse> => {

  const res = await fetch(getNotificationsReadAllUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notificationsReadAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsReadAllResponse
}





export const getNotificationsReadAllQueryKey = () => {
    return [
    'POST', `http://localhost:8000/api/v1/notifications/read-all`
    ] as const;
    }


export const getNotificationsReadAllQueryOptions = <TData = Awaited<ReturnType<typeof notificationsReadAll>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsReadAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsReadAll>>> = ({ signal }) => notificationsReadAll({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsReadAllQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsReadAll>>>
export type NotificationsReadAllQueryError = AuthenticationExceptionResponse


export function useNotificationsReadAll<TData = Awaited<ReturnType<typeof notificationsReadAll>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsReadAll>>,
          TError,
          Awaited<ReturnType<typeof notificationsReadAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsReadAll<TData = Awaited<ReturnType<typeof notificationsReadAll>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsReadAll>>,
          TError,
          Awaited<ReturnType<typeof notificationsReadAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsReadAll<TData = Awaited<ReturnType<typeof notificationsReadAll>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsReadAll<TData = Awaited<ReturnType<typeof notificationsReadAll>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsReadAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsReadAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationsIndexResponse200 = {
  data: NotificationsIndex200
  status: 200
}

export type notificationsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type notificationsIndexResponseSuccess = (notificationsIndexResponse200) & {
  headers: Headers;
};
export type notificationsIndexResponseError = (notificationsIndexResponse401) & {
  headers: Headers;
};

export type notificationsIndexResponse = (notificationsIndexResponseSuccess | notificationsIndexResponseError)

export const getNotificationsIndexUrl = () => {




  return `http://localhost:8000/api/v1/notifications`
}

export const notificationsIndex = async ( options?: RequestInit): Promise<notificationsIndexResponse> => {

  const res = await fetch(getNotificationsIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notificationsIndexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsIndexResponse
}





export const getNotificationsIndexQueryKey = () => {
    return [
    `http://localhost:8000/api/v1/notifications`
    ] as const;
    }


export const getNotificationsIndexQueryOptions = <TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsIndex>>> = ({ signal }) => notificationsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsIndex>>>
export type NotificationsIndexQueryError = AuthenticationExceptionResponse


export function useNotificationsIndex<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsIndex>>,
          TError,
          Awaited<ReturnType<typeof notificationsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsIndex<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsIndex>>,
          TError,
          Awaited<ReturnType<typeof notificationsIndex>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsIndex<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsIndex<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getNotificationsIndexSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsIndex>>> = ({ signal }) => notificationsIndex({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsIndexSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsIndex>>>
export type NotificationsIndexSuspenseQueryError = AuthenticationExceptionResponse


export function useNotificationsIndexSuspense<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsIndexSuspense<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsIndexSuspense<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsIndexSuspense<TData = Awaited<ReturnType<typeof notificationsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof notificationsIndex>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsIndexSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationsReadResponse200 = {
  data: NotificationsRead200
  status: 200
}

export type notificationsReadResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type notificationsReadResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type notificationsReadResponseSuccess = (notificationsReadResponse200) & {
  headers: Headers;
};
export type notificationsReadResponseError = (notificationsReadResponse401 | notificationsReadResponse404) & {
  headers: Headers;
};

export type notificationsReadResponse = (notificationsReadResponseSuccess | notificationsReadResponseError)

export const getNotificationsReadUrl = (notification: string,) => {




  return `http://localhost:8000/api/v1/notifications/${notification}/read`
}

export const notificationsRead = async (notification: string, options?: RequestInit): Promise<notificationsReadResponse> => {

  const res = await fetch(getNotificationsReadUrl(notification),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notificationsReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsReadResponse
}





export const getNotificationsReadQueryKey = (notification: string,) => {
    return [
    'POST', `http://localhost:8000/api/v1/notifications/${notification}/read`
    ] as const;
    }


export const getNotificationsReadQueryOptions = <TData = Awaited<ReturnType<typeof notificationsRead>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(notification: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationsReadQueryKey(notification);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationsRead>>> = ({ signal }) => notificationsRead(notification, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: notification !== null && notification !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationsReadQueryResult = NonNullable<Awaited<ReturnType<typeof notificationsRead>>>
export type NotificationsReadQueryError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse


export function useNotificationsRead<TData = Awaited<ReturnType<typeof notificationsRead>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 notification: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsRead>>,
          TError,
          Awaited<ReturnType<typeof notificationsRead>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsRead<TData = Awaited<ReturnType<typeof notificationsRead>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 notification: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsRead>>,
          TError,
          Awaited<ReturnType<typeof notificationsRead>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationsRead<TData = Awaited<ReturnType<typeof notificationsRead>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 notification: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationsRead<TData = Awaited<ReturnType<typeof notificationsRead>>, TError = AuthenticationExceptionResponse | ModelNotFoundExceptionResponse>(
 notification: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationsRead>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationsReadQueryOptions(notification,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






